-- FORWARD DP balde 2 (5 tabelas suspeitas funcionarios, vazias, sem FK) 2026-06-18
BEGIN;
CREATE TABLE IF NOT EXISTS employee_documents (
	id UUID NOT NULL,
	condominio_id UUID NOT NULL,
	employee_id UUID NOT NULL,
	document_code VARCHAR(50) NOT NULL,
	document_type VARCHAR(50) NOT NULL,
	status VARCHAR(30) NOT NULL,
	title VARCHAR(200) NOT NULL,
	description TEXT,
	category VARCHAR(50),
	tags JSONB,
	file_name VARCHAR(255) NOT NULL,
	file_path VARCHAR(500) NOT NULL,
	file_size INTEGER,
	file_type VARCHAR(50),
	file_hash VARCHAR(64),
	reference_date DATE,
	reference_month INTEGER,
	reference_year INTEGER,
	valid_from DATE,
	valid_until DATE,
	is_perpetual BOOLEAN,
	is_visible BOOLEAN,
	requires_acknowledgement BOOLEAN,
	is_confidential BOOLEAN,
	is_mandatory BOOLEAN,
	first_viewed_at TIMESTAMP WITHOUT TIME ZONE,
	view_count INTEGER,
	last_viewed_at TIMESTAMP WITHOUT TIME ZONE,
	downloaded_at TIMESTAMP WITHOUT TIME ZONE,
	download_count INTEGER,
	acknowledged_at TIMESTAMP WITHOUT TIME ZONE,
	acknowledgement_ip VARCHAR(45),
	acknowledgement_device VARCHAR(200),
	requires_signature BOOLEAN,
	signed_at TIMESTAMP WITHOUT TIME ZONE,
	signed_by UUID,
	signature_hash VARCHAR(64),
	signature_certificate TEXT,
	notification_sent BOOLEAN,
	notification_sent_at TIMESTAMP WITHOUT TIME ZONE,
	reminder_sent BOOLEAN,
	reminder_sent_at TIMESTAMP WITHOUT TIME ZONE,
	parent_document_id UUID,
	related_documents JSONB,
	document_extra_metadata JSONB,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	updated_at TIMESTAMP WITHOUT TIME ZONE,
	created_by UUID,
	published_at TIMESTAMP WITHOUT TIME ZONE,
	published_by UUID,
	archived_at TIMESTAMP WITHOUT TIME ZONE,
	archived_by UUID,
	PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS employee_notifications (
	id UUID NOT NULL,
	condominio_id UUID NOT NULL,
	employee_id UUID NOT NULL,
	notification_type VARCHAR(50) NOT NULL,
	priority VARCHAR(20) NOT NULL,
	title VARCHAR(200) NOT NULL,
	message TEXT NOT NULL,
	short_message VARCHAR(200),
	icon VARCHAR(50),
	color VARCHAR(20),
	image_url VARCHAR(500),
	action_url VARCHAR(500),
	action_label VARCHAR(50),
	action_type VARCHAR(30),
	reference_type VARCHAR(50),
	reference_id UUID,
	channels JSONB,
	delivered_channels JSONB,
	is_read BOOLEAN,
	read_at TIMESTAMP WITHOUT TIME ZONE,
	clicked_at TIMESTAMP WITHOUT TIME ZONE,
	dismissed_at TIMESTAMP WITHOUT TIME ZONE,
	email_sent BOOLEAN,
	email_sent_at TIMESTAMP WITHOUT TIME ZONE,
	email_opened BOOLEAN,
	email_opened_at TIMESTAMP WITHOUT TIME ZONE,
	email_clicked BOOLEAN,
	email_clicked_at TIMESTAMP WITHOUT TIME ZONE,
	push_sent BOOLEAN,
	push_sent_at TIMESTAMP WITHOUT TIME ZONE,
	push_received BOOLEAN,
	push_received_at TIMESTAMP WITHOUT TIME ZONE,
	push_clicked BOOLEAN,
	push_clicked_at TIMESTAMP WITHOUT TIME ZONE,
	sms_sent BOOLEAN,
	sms_sent_at TIMESTAMP WITHOUT TIME ZONE,
	sms_delivered BOOLEAN,
	sms_delivered_at TIMESTAMP WITHOUT TIME ZONE,
	scheduled_at TIMESTAMP WITHOUT TIME ZONE,
	expires_at TIMESTAMP WITHOUT TIME ZONE,
	is_recurring BOOLEAN,
	recurrence_pattern VARCHAR(50),
	next_occurrence TIMESTAMP WITHOUT TIME ZONE,
	extra_data JSONB,
	is_active BOOLEAN,
	is_archived BOOLEAN,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	updated_at TIMESTAMP WITHOUT TIME ZONE,
	created_by UUID,
	PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS employee_payroll_configs (
	id UUID NOT NULL,
	condominio_id UUID NOT NULL,
	employee_id UUID NOT NULL,
	contract_type VARCHAR(30) NOT NULL,
	admission_date DATE NOT NULL,
	termination_date DATE,
	experience_end_date DATE,
	base_salary NUMERIC(15, 2) NOT NULL,
	salary_type VARCHAR(20),
	hourly_rate NUMERIC(10, 4),
	daily_rate NUMERIC(10, 2),
	work_schedule_type VARCHAR(30) NOT NULL,
	weekly_hours NUMERIC(5, 2),
	daily_hours NUMERIC(5, 2),
	monthly_hours NUMERIC(6, 2),
	work_start TIME WITHOUT TIME ZONE,
	work_end TIME WITHOUT TIME ZONE,
	lunch_start TIME WITHOUT TIME ZONE,
	lunch_end TIME WITHOUT TIME ZONE,
	lunch_duration_minutes INTEGER,
	overtime_rule VARCHAR(20) NOT NULL,
	overtime_rate_50 NUMERIC(5, 2),
	overtime_rate_100 NUMERIC(5, 2),
	overtime_threshold NUMERIC(5, 2),
	night_shift_rate NUMERIC(5, 2),
	night_shift_start TIME WITHOUT TIME ZONE,
	night_shift_end TIME WITHOUT TIME ZONE,
	night_hour_reduction BOOLEAN,
	bank_hours_enabled BOOLEAN,
	bank_hours_policy VARCHAR(20),
	bank_hours_balance NUMERIC(10, 2),
	bank_hours_limit NUMERIC(10, 2),
	bank_hours_hybrid_threshold NUMERIC(10, 2),
	hazard_pay_rate NUMERIC(5, 2),
	unhealthy_pay_rate NUMERIC(5, 2),
	unhealthy_pay_base VARCHAR(20),
	benefits JSONB,
	loans JSONB,
	alimony JSONB,
	dependents_count INTEGER,
	dependents JSONB,
	union_id VARCHAR(50),
	union_contribution_enabled BOOLEAN,
	union_contribution_type VARCHAR(20),
	union_contribution_value NUMERIC(10, 2),
	calculation_config JSONB,
	external_codes JSONB,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	updated_at TIMESTAMP WITHOUT TIME ZONE,
	created_by UUID,
	ativo BOOLEAN NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT uq_employee_payroll_config UNIQUE (condominio_id, employee_id)
);
CREATE TABLE IF NOT EXISTS employee_preferences (
	id UUID NOT NULL,
	condominio_id UUID NOT NULL,
	employee_id UUID NOT NULL,
	theme VARCHAR(20),
	language VARCHAR(10),
	font_size VARCHAR(10),
	compact_mode BOOLEAN,
	animations_enabled BOOLEAN,
	notifications_enabled BOOLEAN,
	notification_sound BOOLEAN,
	notification_badge BOOLEAN,
	email_notifications_enabled BOOLEAN,
	email_payslip BOOLEAN,
	email_documents BOOLEAN,
	email_vacation BOOLEAN,
	email_announcements BOOLEAN,
	email_birthday BOOLEAN,
	email_digest BOOLEAN,
	email_digest_time VARCHAR(5),
	push_notifications_enabled BOOLEAN,
	push_payslip BOOLEAN,
	push_documents BOOLEAN,
	push_vacation BOOLEAN,
	push_announcements BOOLEAN,
	push_time_entry BOOLEAN,
	push_quiet_hours BOOLEAN,
	push_quiet_start VARCHAR(5),
	push_quiet_end VARCHAR(5),
	sms_notifications_enabled BOOLEAN,
	sms_urgent_only BOOLEAN,
	whatsapp_notifications_enabled BOOLEAN,
	whatsapp_phone VARCHAR(20),
	dashboard_layout VARCHAR(20),
	dashboard_widgets JSONB,
	default_page VARCHAR(50),
	payslip_auto_download BOOLEAN,
	payslip_notification_day BOOLEAN,
	vacation_reminder_days JSONB,
	vacation_balance_notification BOOLEAN,
	time_entry_reminder BOOLEAN,
	time_entry_reminder_times JSONB,
	time_entry_geofence_reminder BOOLEAN,
	show_birthday BOOLEAN,
	show_photo BOOLEAN,
	show_department BOOLEAN,
	show_position BOOLEAN,
	allow_colleague_contact BOOLEAN,
	two_factor_enabled BOOLEAN,
	two_factor_method VARCHAR(20),
	session_timeout_minutes BOOLEAN,
	remember_device BOOLEAN,
	screen_reader_mode BOOLEAN,
	keyboard_navigation BOOLEAN,
	reduce_motion BOOLEAN,
	color_blind_mode VARCHAR(20),
	trusted_devices JSONB,
	last_login_at TIMESTAMP WITHOUT TIME ZONE,
	last_login_ip VARCHAR(45),
	last_login_device VARCHAR(200),
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	updated_at TIMESTAMP WITHOUT TIME ZONE,
	PRIMARY KEY (id),
	CONSTRAINT uq_employee_preferences UNIQUE (condominio_id, employee_id)
);
CREATE TABLE IF NOT EXISTS payroll_events (
	id UUID NOT NULL,
	condominio_id UUID NOT NULL,
	period_id UUID NOT NULL,
	employee_id UUID NOT NULL,
	event_code VARCHAR(20) NOT NULL,
	event_name VARCHAR(100) NOT NULL,
	event_type VARCHAR(20) NOT NULL,
	event_category VARCHAR(50) NOT NULL,
	reference NUMERIC(10, 2),
	reference_unit VARCHAR(20),
	base_value NUMERIC(15, 2),
	rate NUMERIC(8, 4),
	value NUMERIC(15, 2) NOT NULL,
	source VARCHAR(50),
	source_id UUID,
	calculation_formula TEXT,
	event_date DATE,
	event_start DATE,
	event_end DATE,
	esocial_code VARCHAR(20),
	esocial_incidences JSONB,
	status VARCHAR(20) NOT NULL,
	is_recurring BOOLEAN,
	is_proportional BOOLEAN,
	original_value NUMERIC(15, 2),
	adjustment_reason TEXT,
	adjusted_by UUID,
	adjusted_at TIMESTAMP WITHOUT TIME ZONE,
	notes TEXT,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	updated_at TIMESTAMP WITHOUT TIME ZONE,
	created_by UUID,
	ativo BOOLEAN NOT NULL,
	PRIMARY KEY (id)
);
COMMIT;
