-- FORWARD — Rodada 7: setor por alocação + instruções de posto (2026-07-08)
-- SETOR vem da planilha oficial da folha (PORTARIA/RONDISTA/SERVICOS GERAIS/INSALUBRIDADE).
ALTER TABLE allocations ADD COLUMN IF NOT EXISTS setor VARCHAR(30);

CREATE TABLE IF NOT EXISTS operacional_post_orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  post_id UUID NOT NULL UNIQUE REFERENCES posts(id),
  titulo VARCHAR(200) NOT NULL DEFAULT 'Instruções do posto',
  conteudo TEXT NOT NULL,
  versao INTEGER NOT NULL DEFAULT 1,
  historico JSONB NOT NULL DEFAULT '[]'::jsonb,
  updated_by_nome VARCHAR(200),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Seed do SETOR (planilha ESCALAS JUNHO 2026 ATUALIZADO.xlsx, por pessoa)
CREATE TEMP TABLE setor_map (nome text PRIMARY KEY, setor text);
INSERT INTO setor_map VALUES
 ('ADEILSON DINIZ DEODATO','PORTARIA'),('ANTONIO WALCICLEY PEREIRA DA SILVA','RONDISTA'),
 ('CELIANE GARCIA DE SOUSA','SERVICOS GERAIS'),('DANIEL SOUZA DOS SANTOS','PORTARIA'),
 ('DANIEL VIDAL LARROQUE','INSALUBRIDADE'),('EDILENE SALES SOUSA','SERVICOS GERAIS'),
 ('EULER FELIPE FERNANDES DA COSTA','RONDISTA'),('GEILSON RODRIGUES DE ANDRADE','INSALUBRIDADE'),
 ('JONHATA DINIZ BENAION','RONDISTA'),('JONILSON MARTINS DE SOUZA','RONDISTA'),
 ('LIVIA CARISE PEREIRA CONSENTINE','PORTARIA'),('MAIARA MUNIZ DE SANTOS','PORTARIA'),
 ('OSCAR SOARES DA COSTA FILHO','INSALUBRIDADE'),('ADEMIR SALUSTIANO DE SOUZA FILHO','INSALUBRIDADE'),
 ('FERNANDO SOUZA SIMPLICIO JUNIOR','PORTARIA'),('EDWARD JOSÉ ATENCIO DOMINGUEZ','PORTARIA'),
 ('JEOVANE DO NASCIMENTO','PORTARIA'),('MEIRE GABRIELA DA SILVA E SILVA','PORTARIA'),
 ('ANTONIO CARLOS VIEIRA','INSALUBRIDADE'),('FERNANDO MIGUEL GOMES DA SILVA','INSALUBRIDADE'),
 ('KALEL SILVA DE JESUS','INSALUBRIDADE'),('AILTON CÉSAR VASCONCELOS','RONDISTA'),
 ('ANTONIO CARLOS CASTRO GAMA','RONDISTA'),('EDIWILSON CORREA MARQUES','RONDISTA'),
 ('EDUARDO OLIVEIRA DE SOUZA','RONDISTA'),('MAURICIO ALVES CHAGAS','PORTARIA'),
 ('PAULO DA SILVA LAMEGO','INSALUBRIDADE'),('TELMA MARIA LAGES MEIRA','SERVICOS GERAIS'),
 ('VANDERLICE SANTOS DA SILVA','SERVICOS GERAIS'),('ANTONIO DINIZ ASSIS DOS SANTOS','RONDISTA'),
 ('CARLOS EDUARDO DA SILVA FAÇANHA','PORTARIA'),('GRACIENE PEREIRA DE CASTRO','INSALUBRIDADE'),
 ('KEYSON DA SILVA PINTO','PORTARIA'),('MALAQUIAS PEREIRA FERREIRA','INSALUBRIDADE'),
 ('RILEM FERREIRA DE SOUZA','RONDISTA'),('ANGELA LOPES MACEDO','INSALUBRIDADE'),
 ('CINTIA BEZERRA OLIVEIRA','PORTARIA'),('EIDY CULIER DE CASTRO','PORTARIA'),
 ('GERNANES BINDA APARICIO','PORTARIA'),('JAQUELINE CARLOS DOS SANTOS','INSALUBRIDADE'),
 ('RENE RICARDO CRUZ GONÇALVES','PORTARIA'),('RUAN RODRIGUES FIGUEIREDO','PORTARIA'),
 ('ADAILSON SERRA ALVES','RONDISTA'),('ANDREA GONÇALVES DOS SANTOS','PORTARIA'),
 ('ANILSON JOSE SEIXAS NEVES','RONDISTA'),('BIANCA HELEM DA SILVA MEIRA','PORTARIA'),
 ('ELEN XAVIER NUNES','PORTARIA'),('ERIKA CRISTINA MAQUINE PEREIRA','PORTARIA'),
 ('FRANCISCO RAMON FARIAS DE SOUZA','RONDISTA'),('JONATHAN DO NASCIMENTO MENDES','PORTARIA'),
 ('MATHEUS HENRIQUE CABRAL DA SILVA','RONDISTA');

UPDATE allocations a SET setor=m.setor, updated_at=now()
FROM employees e, setor_map m
WHERE a.employee_id=e.id AND e.nome=m.nome AND a.is_active AND a.setor IS DISTINCT FROM m.setor;

SELECT 'setor seedado', setor, count(*) FROM allocations WHERE is_active AND status='active' AND setor IS NOT NULL GROUP BY setor;
SELECT 'ativos sem setor', count(*) FROM allocations a JOIN employees e ON e.id=a.employee_id
WHERE a.is_active AND a.status='active' AND e.status='ativo' AND a.setor IS NULL;
