DO $$ BEGIN CREATE TYPE tipodocumentofiscal AS ENUM ('RPA', 'NFSE', 'RECIBO_SIMPLES', 'DECLARACAO'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE statusdocumentofiscal AS ENUM ('RASCUNHO', 'EMITIDO', 'CANCELADO', 'SUBSTITUIDO'); EXCEPTION WHEN duplicate_object THEN null; END $$;
CREATE TABLE IF NOT EXISTS documentos_fiscais_diaristas (
	id UUID NOT NULL, 
	numero VARCHAR(50) NOT NULL, 
	tipo tipodocumentofiscal NOT NULL, 
	status statusdocumentofiscal NOT NULL, 
	diarist_id UUID NOT NULL, 
	payment_id UUID, 
	competencia VARCHAR(7) NOT NULL, 
	data_emissao DATE NOT NULL, 
	data_pagamento DATE, 
	valor_bruto NUMERIC(12, 2) NOT NULL, 
	valor_inss NUMERIC(12, 2) NOT NULL, 
	valor_iss NUMERIC(12, 2) NOT NULL, 
	valor_irrf NUMERIC(12, 2) NOT NULL, 
	valor_outras_retencoes NUMERIC(12, 2) NOT NULL, 
	valor_liquido NUMERIC(12, 2) NOT NULL, 
	prestador_cpf VARCHAR(14) NOT NULL, 
	prestador_nome VARCHAR(200) NOT NULL, 
	prestador_endereco VARCHAR(500), 
	prestador_municipio VARCHAR(100), 
	prestador_uf VARCHAR(2), 
	prestador_pis VARCHAR(20), 
	tomador_cnpj VARCHAR(18) NOT NULL, 
	tomador_razao_social VARCHAR(200) NOT NULL, 
	tomador_endereco VARCHAR(500), 
	descricao_servico TEXT NOT NULL, 
	codigo_servico VARCHAR(20), 
	cnae VARCHAR(10), 
	base_calculo_inss NUMERIC(12, 2), 
	aliquota_inss NUMERIC(5, 2), 
	base_calculo_iss NUMERIC(12, 2), 
	aliquota_iss NUMERIC(5, 2), 
	base_calculo_irrf NUMERIC(12, 2), 
	aliquota_irrf NUMERIC(5, 2), 
	observacoes TEXT, 
	historico_alteracoes JSONB, 
	nfse_numero VARCHAR(50), 
	nfse_codigo_verificacao VARCHAR(100), 
	nfse_url VARCHAR(500), 
	pdf_url VARCHAR(500), 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	created_by UUID, 
	is_active BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (numero)
);
DO $$ BEGIN CREATE TYPE tipoeventoesocial AS ENUM ('S2300', 'S2306', 'S2399', 'S1200', 'S1210'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE statuseventoesocial AS ENUM ('PENDENTE', 'ENVIADO', 'PROCESSANDO', 'ACEITO', 'REJEITADO', 'RETIFICADO'); EXCEPTION WHEN duplicate_object THEN null; END $$;
CREATE TABLE IF NOT EXISTS eventos_esocial_diaristas (
	id UUID NOT NULL, 
	tipo_evento tipoeventoesocial NOT NULL, 
	status statuseventoesocial NOT NULL, 
	diarist_id UUID NOT NULL, 
	documento_id UUID, 
	competencia VARCHAR(7) NOT NULL, 
	id_evento VARCHAR(50), 
	numero_recibo VARCHAR(100), 
	xml_envio TEXT, 
	xml_retorno TEXT, 
	dados_evento JSONB, 
	data_envio TIMESTAMP WITHOUT TIME ZONE, 
	data_processamento TIMESTAMP WITHOUT TIME ZONE, 
	mensagem_retorno TEXT, 
	codigo_retorno VARCHAR(20), 
	evento_retificado_id UUID, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE, 
	created_by UUID, 
	PRIMARY KEY (id), 
	UNIQUE (id_evento)
);
DO $$ BEGIN CREATE TYPE tiporetencao AS ENUM ('INSS', 'ISS', 'IRRF', 'PIS', 'COFINS', 'CSLL'); EXCEPTION WHEN duplicate_object THEN null; END $$;
CREATE TABLE IF NOT EXISTS retencoes_fiscais_diaristas (
	id UUID NOT NULL, 
	documento_id UUID NOT NULL, 
	tipo tiporetencao NOT NULL, 
	base_calculo NUMERIC(12, 2) NOT NULL, 
	aliquota NUMERIC(5, 2) NOT NULL, 
	valor NUMERIC(12, 2) NOT NULL, 
	fundamentacao_legal VARCHAR(200), 
	codigo_receita VARCHAR(20), 
	observacoes TEXT, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);
