"""Camada 3 - financial_kpis (zona financial/): CREATE kpi_trend_enum + ADD 29 colunas. Dado preservado, legadas mantidas."""
from alembic import op
revision="camada3_financial_kpis"; down_revision="camada3_benchmarks"; branch_labels=None; depends_on=None
STMTS=["CREATE TYPE kpi_trend_enum AS ENUM ('UP','DOWN','STABLE','VOLATILE');", 'ALTER TABLE financial_kpis ADD COLUMN IF NOT EXISTS alert_enabled BOOLEAN;', 'ALTER TABLE financial_kpis ADD COLUMN IF NOT EXISTS alert_message TEXT;', 'ALTER TABLE financial_kpis ADD COLUMN IF NOT EXISTS benchmark_data TIMESTAMPTZ;', 'ALTER TABLE financial_kpis ADD COLUMN IF NOT EXISTS benchmark_fonte VARCHAR(200);', 'ALTER TABLE financial_kpis ADD COLUMN IF NOT EXISTS benchmark_valor NUMERIC(20,4);', 'ALTER TABLE financial_kpis ADD COLUMN IF NOT EXISTS color VARCHAR(20);', 'ALTER TABLE financial_kpis ADD COLUMN IF NOT EXISTS created_by UUID;', 'ALTER TABLE financial_kpis ADD COLUMN IF NOT EXISTS data_sources JSONB;', 'ALTER TABLE financial_kpis ADD COLUMN IF NOT EXISTS formula_descricao TEXT;', 'ALTER TABLE financial_kpis ADD COLUMN IF NOT EXISTS historico_dias INTEGER;', 'ALTER TABLE financial_kpis ADD COLUMN IF NOT EXISTS historico_valores JSONB;', 'ALTER TABLE financial_kpis ADD COLUMN IF NOT EXISTS icon VARCHAR(100);', 'ALTER TABLE financial_kpis ADD COLUMN IF NOT EXISTS is_inverted BOOLEAN;', 'ALTER TABLE financial_kpis ADD COLUMN IF NOT EXISTS is_percentage BOOLEAN;', 'ALTER TABLE financial_kpis ADD COLUMN IF NOT EXISTS meta_atingida BOOLEAN;', 'ALTER TABLE financial_kpis ADD COLUMN IF NOT EXISTS meta_maximo NUMERIC(20,4);', 'ALTER TABLE financial_kpis ADD COLUMN IF NOT EXISTS meta_minimo NUMERIC(20,4);', 'ALTER TABLE financial_kpis ADD COLUMN IF NOT EXISTS meta_percentual NUMERIC(10,2);', 'ALTER TABLE financial_kpis ADD COLUMN IF NOT EXISTS nome_curto VARCHAR(50);', 'ALTER TABLE financial_kpis ADD COLUMN IF NOT EXISTS show_in_summary BOOLEAN;', 'ALTER TABLE financial_kpis ADD COLUMN IF NOT EXISTS tags JSONB;', 'ALTER TABLE financial_kpis ADD COLUMN IF NOT EXISTS threshold_critical_max NUMERIC(20,4);', 'ALTER TABLE financial_kpis ADD COLUMN IF NOT EXISTS threshold_critical_min NUMERIC(20,4);', 'ALTER TABLE financial_kpis ADD COLUMN IF NOT EXISTS threshold_warning_max NUMERIC(20,4);', 'ALTER TABLE financial_kpis ADD COLUMN IF NOT EXISTS threshold_warning_min NUMERIC(20,4);', 'ALTER TABLE financial_kpis ADD COLUMN IF NOT EXISTS trend kpi_trend_enum;', 'ALTER TABLE financial_kpis ADD COLUMN IF NOT EXISTS ultimo_calculo_at TIMESTAMPTZ;', 'ALTER TABLE financial_kpis ADD COLUMN IF NOT EXISTS updated_by UUID;', 'ALTER TABLE financial_kpis ADD COLUMN IF NOT EXISTS variacao_percentual NUMERIC(10,2);']
ADDED=[s.split("EXISTS ")[1].split(" ")[0] for s in STMTS if "ADD COLUMN" in s]
def upgrade():
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname='kpi_trend_enum') THEN CREATE TYPE kpi_trend_enum AS ENUM ('UP','DOWN','STABLE','VOLATILE'); END IF; END $$;")
    for s in STMTS:
        if s.startswith("ALTER TABLE"): op.execute(s)
def downgrade():
    for c in ADDED: op.execute(f"ALTER TABLE financial_kpis DROP COLUMN IF EXISTS {c}")
