"""migrations FIN+DP balde 1+2: cria 17 tabelas (custeio ABC, fiscal, DP-folha) + 324 colunas aditivas

Revision ID: findp_b1b2_20260601
Revises: drop_openclaw_tables
Create Date: 2026-06-01

Aplicada via script de metadados do model (apply_findp.py) em staging->producao 2026-06-01.
Apenas CREATE TABLE (vazias, sem FK) e ADD COLUMN aditivo. Zero dado tocado.
SQL completo: auditoria/FORWARD_* e auditoria/REVERSAO_*.
"""
from alembic import op

revision = "findp_b1b2_20260601"
down_revision = "drop_openclaw_tables"
branch_labels = None
depends_on = None

FORWARD = [
"CREATE TABLE IF NOT EXISTS ecd_resumos (\n\tid UUID NOT NULL, \n\tsped_file_id UUID NOT NULL, \n\tcondominio_id UUID NOT NULL, \n\tano INTEGER NOT NULL, \n\tdata_inicio DATE NOT NULL, \n\tdata_fim DATE NOT NULL, \n\ttipo_ecd VARCHAR(1) NOT NULL, \n\ttotal_ativo NUMERIC(15, 2) NOT NULL, \n\ttotal_passivo NUMERIC(15, 2) NOT NULL, \n\tpatrimonio_liquido NUMERIC(15, 2) NOT NULL, \n\ttotal_receitas NUMERIC(15, 2) NOT NULL, \n\ttotal_despesas NUMERIC(15, 2) NOT NULL, \n\tresultado_exercicio NUMERIC(15, 2) NOT NULL, \n\tqtd_lancamentos INTEGER NOT NULL, \n\tqtd_contas INTEGER NOT NULL, \n\tqtd_centros_custo INTEGER NOT NULL, \n\ttermo_abertura TEXT, \n\ttermo_encerramento TEXT, \n\thash_abertura VARCHAR(64), \n\thash_encerramento VARCHAR(64), \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE, \n\tPRIMARY KEY (id)\n)",
"CREATE TABLE IF NOT EXISTS efd_contribuicoes_resumos (\n\tid UUID NOT NULL, \n\tsped_file_id UUID NOT NULL, \n\tcondominio_id UUID NOT NULL, \n\tano INTEGER NOT NULL, \n\tmes INTEGER NOT NULL, \n\treceita_bruta_cumulativo NUMERIC(15, 2) NOT NULL, \n\treceita_bruta_nao_cumulativo NUMERIC(15, 2) NOT NULL, \n\treceita_bruta_total NUMERIC(15, 2) NOT NULL, \n\tpis_base_calculo NUMERIC(15, 2) NOT NULL, \n\tpis_debito NUMERIC(15, 2) NOT NULL, \n\tpis_credito NUMERIC(15, 2) NOT NULL, \n\tpis_saldo_credor_anterior NUMERIC(15, 2) NOT NULL, \n\tpis_a_recolher NUMERIC(15, 2) NOT NULL, \n\tpis_saldo_credor NUMERIC(15, 2) NOT NULL, \n\tcofins_base_calculo NUMERIC(15, 2) NOT NULL, \n\tcofins_debito NUMERIC(15, 2) NOT NULL, \n\tcofins_credito NUMERIC(15, 2) NOT NULL, \n\tcofins_saldo_credor_anterior NUMERIC(15, 2) NOT NULL, \n\tcofins_a_recolher NUMERIC(15, 2) NOT NULL, \n\tcofins_saldo_credor NUMERIC(15, 2) NOT NULL, \n\tpis_retido NUMERIC(15, 2) NOT NULL, \n\tcofins_retido NUMERIC(15, 2) NOT NULL, \n\tqtd_documentos_receitas INTEGER NOT NULL, \n\tqtd_documentos_creditos INTEGER NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE, \n\tPRIMARY KEY (id)\n)",
"CREATE TABLE IF NOT EXISTS efd_icms_ipi_resumos (\n\tid UUID NOT NULL, \n\tsped_file_id UUID NOT NULL, \n\tcondominio_id UUID NOT NULL, \n\tano INTEGER NOT NULL, \n\tmes INTEGER NOT NULL, \n\tvalor_contabil_entradas NUMERIC(15, 2) NOT NULL, \n\tbase_icms_entradas NUMERIC(15, 2) NOT NULL, \n\ticms_entradas NUMERIC(15, 2) NOT NULL, \n\tipi_entradas NUMERIC(15, 2) NOT NULL, \n\tvalor_contabil_saidas NUMERIC(15, 2) NOT NULL, \n\tbase_icms_saidas NUMERIC(15, 2) NOT NULL, \n\ticms_saidas NUMERIC(15, 2) NOT NULL, \n\tipi_saidas NUMERIC(15, 2) NOT NULL, \n\ticms_st_entradas NUMERIC(15, 2) NOT NULL, \n\ticms_st_saidas NUMERIC(15, 2) NOT NULL, \n\ticms_debito NUMERIC(15, 2) NOT NULL, \n\ticms_credito NUMERIC(15, 2) NOT NULL, \n\ticms_saldo_credor_anterior NUMERIC(15, 2) NOT NULL, \n\ticms_outros_debitos NUMERIC(15, 2) NOT NULL, \n\ticms_outros_creditos NUMERIC(15, 2) NOT NULL, \n\ticms_estorno_debito NUMERIC(15, 2) NOT NULL, \n\ticms_estorno_credito NUMERIC(15, 2) NOT NULL, \n\ticms_saldo_devedor NUMERIC(15, 2) NOT NULL, \n\ticms_saldo_credor NUMERIC(15, 2) NOT NULL, \n\ticms_a_recolher NUMERIC(15, 2) NOT NULL, \n\tipi_debito NUMERIC(15, 2) NOT NULL, \n\tipi_credito NUMERIC(15, 2) NOT NULL, \n\tipi_saldo_credor_anterior NUMERIC(15, 2) NOT NULL, \n\tipi_a_recolher NUMERIC(15, 2) NOT NULL, \n\tipi_saldo_credor NUMERIC(15, 2) NOT NULL, \n\tqtd_documentos_entradas INTEGER NOT NULL, \n\tqtd_documentos_saidas INTEGER NOT NULL, \n\tqtd_itens INTEGER NOT NULL, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE, \n\tPRIMARY KEY (id)\n)",
"CREATE TABLE IF NOT EXISTS fin_cost_analyses (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tcondominio_id UUID NOT NULL, \n\tcode VARCHAR(30) NOT NULL, \n\tname VARCHAR(150) NOT NULL, \n\tdescription TEXT, \n\tanalysis_type analysistype NOT NULL, \n\tstatus analysisstatus NOT NULL, \n\tscope analysisscope NOT NULL, \n\tperiod_start TIMESTAMP WITH TIME ZONE NOT NULL, \n\tperiod_end TIMESTAMP WITH TIME ZONE NOT NULL, \n\treference_period VARCHAR(7), \n\tcost_center_ids JSONB, \n\tactivity_ids JSONB, \n\tpool_ids JSONB, \n\tobject_ids JSONB, \n\tfilters JSONB, \n\tparameters JSONB, \n\tscenarios JSONB, \n\tcomparison_period_start TIMESTAMP WITH TIME ZONE, \n\tcomparison_period_end TIMESTAMP WITH TIME ZONE, \n\tresults JSONB, \n\ttotal_cost NUMERIC(18, 2) NOT NULL, \n\ttotal_revenue NUMERIC(18, 2) NOT NULL, \n\ttotal_margin NUMERIC(18, 2) NOT NULL, \n\tmargin_percent NUMERIC(8, 4) NOT NULL, \n\ttotal_direct_cost NUMERIC(18, 2) NOT NULL, \n\ttotal_indirect_cost NUMERIC(18, 2) NOT NULL, \n\ttotal_allocated NUMERIC(18, 2) NOT NULL, \n\tunallocated_cost NUMERIC(18, 2) NOT NULL, \n\tpractical_capacity NUMERIC(18, 4), \n\tused_capacity NUMERIC(18, 4), \n\tidle_capacity NUMERIC(18, 4), \n\tidle_capacity_cost NUMERIC(18, 2), \n\tcost_variance NUMERIC(18, 2), \n\tvolume_variance NUMERIC(18, 2), \n\tefficiency_variance NUMERIC(18, 2), \n\tprice_variance NUMERIC(18, 2), \n\tbreak_even_units NUMERIC(18, 4), \n\tbreak_even_revenue NUMERIC(18, 2), \n\tsafety_margin NUMERIC(18, 2), \n\tsafety_margin_percent NUMERIC(8, 4), \n\tinsights JSONB, \n\trecommendations JSONB, \n\talerts JSONB, \n\tcharts_data JSONB, \n\tstarted_at TIMESTAMP WITH TIME ZONE, \n\tcompleted_at TIMESTAMP WITH TIME ZONE, \n\texecution_time_ms INTEGER, \n\terror_message TEXT, \n\treport_format reportformat, \n\treport_path VARCHAR(300), \n\treport_generated_at TIMESTAMP WITH TIME ZONE, \n\tis_scheduled BOOLEAN NOT NULL, \n\tschedule_cron VARCHAR(50), \n\tnext_run_at TIMESTAMP WITH TIME ZONE, \n\tlast_run_at TIMESTAMP WITH TIME ZONE, \n\tshared_with JSONB, \n\tis_public BOOLEAN NOT NULL, \n\tis_template BOOLEAN NOT NULL, \n\tis_favorite BOOLEAN NOT NULL, \n\tactive BOOLEAN NOT NULL, \n\tnotes TEXT, \n\ttags JSONB, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by UUID, \n\tupdated_by UUID, \n\tdeleted_by UUID, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_cost_analysis_code UNIQUE (condominio_id, code)\n)",
"CREATE TABLE IF NOT EXISTS fin_cost_drivers (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tcondominio_id UUID NOT NULL, \n\tcode VARCHAR(30) NOT NULL, \n\tname VARCHAR(100) NOT NULL, \n\tdescription TEXT, \n\tdriver_type drivertype NOT NULL, \n\tdriver_category drivercategory NOT NULL, \n\tstatus driverstatus NOT NULL, \n\tmeasure_unit drivermeasureunit NOT NULL, \n\tmeasure_symbol VARCHAR(10), \n\tunit_cost NUMERIC(18, 6) NOT NULL, \n\tunit_cost_currency VARCHAR(3) NOT NULL, \n\tpractical_capacity NUMERIC(18, 4), \n\ttheoretical_capacity NUMERIC(18, 4), \n\tused_capacity NUMERIC(18, 4) NOT NULL, \n\tcustom_formula TEXT, \n\tformula_variables JSONB, \n\tupdate_frequency VARCHAR(20) NOT NULL, \n\tlast_rate_update TIMESTAMP WITH TIME ZONE, \n\tnext_rate_update TIMESTAMP WITH TIME ZONE, \n\trate_history JSONB, \n\tdata_source VARCHAR(100), \n\tsource_table VARCHAR(100), \n\tsource_field VARCHAR(100), \n\tis_automated BOOLEAN NOT NULL, \n\tmin_value NUMERIC(18, 4), \n\tmax_value NUMERIC(18, 4), \n\trequires_validation BOOLEAN NOT NULL, \n\ttotal_allocations INTEGER NOT NULL, \n\ttotal_allocated_amount NUMERIC(18, 2) NOT NULL, \n\taverage_rate NUMERIC(18, 6) NOT NULL, \n\tis_primary BOOLEAN NOT NULL, \n\tis_system BOOLEAN NOT NULL, \n\tactive BOOLEAN NOT NULL, \n\tnotes TEXT, \n\ttags JSONB, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by UUID, \n\tupdated_by UUID, \n\tdeleted_by UUID, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_cost_driver_code UNIQUE (condominio_id, code)\n)",
"CREATE TABLE IF NOT EXISTS fin_cost_objects (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tcondominio_id UUID NOT NULL, \n\tparent_id UUID, \n\treference_type VARCHAR(50), \n\treference_id UUID, \n\tcode VARCHAR(50) NOT NULL, \n\tname VARCHAR(150) NOT NULL, \n\tshort_name VARCHAR(50), \n\tdescription TEXT, \n\tobject_type costobjecttype NOT NULL, \n\tstatus costobjectstatus NOT NULL, \n\tcategory VARCHAR(100), \n\tsubcategory VARCHAR(100), \n\tlevel INTEGER NOT NULL, \n\tpath VARCHAR(300), \n\torder_index INTEGER, \n\trevenue NUMERIC(18, 2) NOT NULL, \n\trevenue_budget NUMERIC(18, 2) NOT NULL, \n\tdirect_material_cost NUMERIC(18, 2) NOT NULL, \n\tdirect_labor_cost NUMERIC(18, 2) NOT NULL, \n\tother_direct_cost NUMERIC(18, 2) NOT NULL, \n\ttotal_direct_cost NUMERIC(18, 2) NOT NULL, \n\tallocated_overhead NUMERIC(18, 2) NOT NULL, \n\tallocated_activity_cost NUMERIC(18, 2) NOT NULL, \n\ttotal_indirect_cost NUMERIC(18, 2) NOT NULL, \n\ttotal_cost NUMERIC(18, 2) NOT NULL, \n\tcost_budget NUMERIC(18, 2) NOT NULL, \n\tcost_variance NUMERIC(18, 2) NOT NULL, \n\tgross_margin NUMERIC(18, 2) NOT NULL, \n\tgross_margin_percent NUMERIC(8, 4) NOT NULL, \n\tcontribution_margin NUMERIC(18, 2) NOT NULL, \n\tcontribution_margin_percent NUMERIC(8, 4) NOT NULL, \n\tnet_margin NUMERIC(18, 2) NOT NULL, \n\tnet_margin_percent NUMERIC(8, 4) NOT NULL, \n\tprofitability_level profitabilitylevel, \n\tprofitability_score NUMERIC(5, 2), \n\tunit_cost NUMERIC(18, 6) NOT NULL, \n\tunit_price NUMERIC(18, 6) NOT NULL, \n\tquantity NUMERIC(18, 4) NOT NULL, \n\tunit_of_measure VARCHAR(20), \n\tcost_breakdown JSONB, \n\tactivities_consumed JSONB, \n\tdrivers_consumed JSONB, \n\tallocations_count INTEGER NOT NULL, \n\tlast_cost_update TIMESTAMP WITH TIME ZONE, \n\treference_period VARCHAR(7), \n\tvalid_from TIMESTAMP WITH TIME ZONE, \n\tvalid_until TIMESTAMP WITH TIME ZONE, \n\towner_id UUID, \n\towner_name VARCHAR(100), \n\tdepartment VARCHAR(100), \n\tis_strategic BOOLEAN NOT NULL, \n\trequires_analysis BOOLEAN NOT NULL, \n\tactive BOOLEAN NOT NULL, \n\tnotes TEXT, \n\ttags JSONB, \n\textra_metadata JSONB, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by UUID, \n\tupdated_by UUID, \n\tdeleted_by UUID, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_cost_object_code UNIQUE (condominio_id, code)\n)",
"CREATE TABLE IF NOT EXISTS fin_cost_pools (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tcondominio_id UUID NOT NULL, \n\tparent_id UUID, \n\tcost_center_id UUID, \n\tcode VARCHAR(30) NOT NULL, \n\tname VARCHAR(100) NOT NULL, \n\tdescription TEXT, \n\tpool_type pooltype NOT NULL, \n\tstatus poolstatus NOT NULL, \n\tallocation_basis allocationbasis NOT NULL, \n\tlevel INTEGER NOT NULL, \n\tpath VARCHAR(200), \n\torder_index INTEGER, \n\ttotal_cost NUMERIC(18, 2) NOT NULL, \n\tallocated_cost NUMERIC(18, 2) NOT NULL, \n\tunallocated_cost NUMERIC(18, 2) NOT NULL, \n\tbudget_amount NUMERIC(18, 2) NOT NULL, \n\tbudget_variance NUMERIC(18, 2) NOT NULL, \n\tallocation_base_quantity NUMERIC(18, 4) NOT NULL, \n\tallocation_rate NUMERIC(18, 6) NOT NULL, \n\trate_currency VARCHAR(3) NOT NULL, \n\tcustom_allocation_formula TEXT, \n\tallocation_weights JSONB, \n\tcost_components JSONB, \n\tactivities_count INTEGER NOT NULL, \n\tallocations_count INTEGER NOT NULL, \n\tlast_allocation_date TIMESTAMP WITH TIME ZONE, \n\treference_period VARCHAR(7), \n\tvalid_from TIMESTAMP WITH TIME ZONE, \n\tvalid_until TIMESTAMP WITH TIME ZONE, \n\tmanager_id UUID, \n\tmanager_name VARCHAR(100), \n\tdepartment VARCHAR(100), \n\tis_homogeneous BOOLEAN NOT NULL, \n\trequires_approval BOOLEAN NOT NULL, \n\tauto_allocate BOOLEAN NOT NULL, \n\tactive BOOLEAN NOT NULL, \n\tnotes TEXT, \n\ttags JSONB, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by UUID, \n\tupdated_by UUID, \n\tdeleted_by UUID, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_cost_pool_code UNIQUE (condominio_id, code)\n)",
"CREATE TABLE IF NOT EXISTS fin_cost_activities (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tcondominio_id UUID NOT NULL, \n\tparent_id UUID, \n\tcost_pool_id UUID, \n\tprimary_driver_id UUID, \n\tcost_center_id UUID, \n\tcode VARCHAR(30) NOT NULL, \n\tname VARCHAR(150) NOT NULL, \n\tshort_name VARCHAR(50), \n\tdescription TEXT, \n\tactivity_type activitytype NOT NULL, \n\tactivity_level activitylevel NOT NULL, \n\tstatus activitystatus NOT NULL, \n\tvalue_added_type valueaddedtype NOT NULL, \n\tlevel INTEGER NOT NULL, \n\tpath VARCHAR(300), \n\torder_index INTEGER, \n\ttotal_cost NUMERIC(18, 2) NOT NULL, \n\tfixed_cost NUMERIC(18, 2) NOT NULL, \n\tvariable_cost NUMERIC(18, 2) NOT NULL, \n\tallocated_cost NUMERIC(18, 2) NOT NULL, \n\tactivity_rate NUMERIC(18, 6) NOT NULL, \n\trate_currency VARCHAR(3) NOT NULL, \n\tpractical_capacity NUMERIC(18, 4), \n\tused_capacity NUMERIC(18, 4) NOT NULL, \n\tcapacity_unit VARCHAR(20), \n\tstandard_time NUMERIC(10, 4), \n\tactual_time NUMERIC(10, 4), \n\ttime_variance NUMERIC(10, 4), \n\texecution_frequency VARCHAR(20) NOT NULL, \n\texecutions_count INTEGER NOT NULL, \n\tlast_execution_at TIMESTAMP WITH TIME ZONE, \n\tresources_consumed JSONB, \n\toutputs_produced JSONB, \n\tsecondary_drivers JSONB, \n\tbenchmark_cost NUMERIC(18, 2), \n\tbenchmark_time NUMERIC(10, 4), \n\tbenchmark_source VARCHAR(100), \n\tprocess_name VARCHAR(100), \n\tsubprocess_name VARCHAR(100), \n\tdepartment VARCHAR(100), \n\tresponsible_id UUID, \n\tresponsible_name VARCHAR(100), \n\tvalid_from TIMESTAMP WITH TIME ZONE, \n\tvalid_until TIMESTAMP WITH TIME ZONE, \n\treference_period VARCHAR(7), \n\tis_core BOOLEAN NOT NULL, \n\tis_outsourceable BOOLEAN NOT NULL, \n\tis_automatable BOOLEAN NOT NULL, \n\trequires_approval BOOLEAN NOT NULL, \n\tactive BOOLEAN NOT NULL, \n\tnotes TEXT, \n\ttags JSONB, \n\textra_metadata JSONB, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by UUID, \n\tupdated_by UUID, \n\tdeleted_by UUID, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_cost_activity_code UNIQUE (condominio_id, code)\n)",
"CREATE TABLE IF NOT EXISTS fin_cost_allocations (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tcondominio_id UUID NOT NULL, \n\tallocation_number VARCHAR(30) NOT NULL, \n\tbatch_id UUID, \n\tbatch_sequence INTEGER, \n\tsource_pool_id UUID, \n\tsource_activity_id UUID, \n\tsource_cost_center_id UUID, \n\tactivity_id UUID, \n\tcost_object_id UUID, \n\ttarget_cost_center_id UUID, \n\tdriver_id UUID, \n\tallocation_type allocationtype NOT NULL, \n\tstatus allocationstatus NOT NULL, \n\tallocation_method allocationmethod_alloc NOT NULL, \n\tdescription VARCHAR(200), \n\treference VARCHAR(100), \n\tallocated_amount NUMERIC(18, 2) NOT NULL, \n\tcurrency VARCHAR(3) NOT NULL, \n\tdriver_quantity NUMERIC(18, 6), \n\tdriver_rate NUMERIC(18, 6), \n\tallocation_percentage NUMERIC(8, 4), \n\tallocation_weight NUMERIC(8, 4), \n\tformula_used TEXT, \n\tformula_variables JSONB, \n\treference_period VARCHAR(7) NOT NULL, \n\tallocation_date TIMESTAMP WITH TIME ZONE NOT NULL, \n\teffective_date TIMESTAMP WITH TIME ZONE, \n\tcost_components JSONB, \n\tis_validated BOOLEAN NOT NULL, \n\tvalidated_at TIMESTAMP WITH TIME ZONE, \n\tvalidated_by UUID, \n\tvalidation_notes TEXT, \n\tapproved_at TIMESTAMP WITH TIME ZONE, \n\tapproved_by UUID, \n\tapproval_notes TEXT, \n\texecuted_at TIMESTAMP WITH TIME ZONE, \n\texecuted_by UUID, \n\tis_reversed BOOLEAN NOT NULL, \n\treversed_at TIMESTAMP WITH TIME ZONE, \n\treversed_by UUID, \n\treversal_reason TEXT, \n\treversal_allocation_id UUID, \n\tjournal_entry_id UUID, \n\tdebit_account_id UUID, \n\tcredit_account_id UUID, \n\tis_posted BOOLEAN NOT NULL, \n\tposted_at TIMESTAMP WITH TIME ZONE, \n\tsource_document VARCHAR(100), \n\tsource_system VARCHAR(50), \n\texternal_reference VARCHAR(100), \n\tis_automatic BOOLEAN NOT NULL, \n\tis_recurring BOOLEAN NOT NULL, \n\trequires_approval BOOLEAN NOT NULL, \n\tactive BOOLEAN NOT NULL, \n\tnotes TEXT, \n\ttags JSONB, \n\textra_metadata JSONB, \n\tcreated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tdeleted_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by UUID, \n\tupdated_by UUID, \n\tdeleted_by UUID, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_cost_allocation_number UNIQUE (condominio_id, allocation_number)\n)",
"CREATE TABLE IF NOT EXISTS financial_analytics_cache (\n\tid UUID NOT NULL, \n\tcondominio_id UUID NOT NULL, \n\tcache_key VARCHAR(255) NOT NULL, \n\ttipo cache_type_enum NOT NULL, \n\tstatus cache_status_enum NOT NULL, \n\tentity_type VARCHAR(100), \n\tentity_id UUID, \n\tquery_hash VARCHAR(64), \n\tdata JSONB NOT NULL, \n\tdata_size_bytes INTEGER, \n\trow_count INTEGER, \n\tparametros JSONB, \n\tperiodo_inicio TIMESTAMP WITHOUT TIME ZONE, \n\tperiodo_fim TIMESTAMP WITHOUT TIME ZONE, \n\tttl_seconds INTEGER NOT NULL, \n\texpires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tis_expired BOOLEAN, \n\thit_count INTEGER NOT NULL, \n\tmiss_count INTEGER NOT NULL, \n\tlast_hit_at TIMESTAMP WITHOUT TIME ZONE, \n\tlast_refresh_at TIMESTAMP WITHOUT TIME ZONE, \n\trefresh_count INTEGER, \n\trefresh_duration_ms INTEGER, \n\tlast_error TEXT, \n\terror_count INTEGER, \n\ttags JSONB, \n\textra_metadata JSONB, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE, \n\tPRIMARY KEY (id)\n)",
"CREATE TABLE IF NOT EXISTS financial_scheduled_reports (\n\tid UUID NOT NULL, \n\tcondominio_id UUID NOT NULL, \n\tcodigo VARCHAR(50) NOT NULL, \n\tnome VARCHAR(200) NOT NULL, \n\tdescricao TEXT, \n\ttipo report_type_enum NOT NULL, \n\tformato report_format_enum NOT NULL, \n\tstatus report_status_enum NOT NULL, \n\tfrequencia report_frequency_enum NOT NULL, \n\thora_execucao TIME WITHOUT TIME ZONE, \n\tdia_semana INTEGER, \n\tdia_mes INTEGER, \n\ttimezone VARCHAR(50), \n\tperiodo_tipo VARCHAR(50), \n\tperiodo_dias INTEGER, \n\tdata_inicio DATE, \n\tdata_fim DATE, \n\tvalido_de DATE, \n\tvalido_ate DATE, \n\tmetodo_entrega delivery_method_enum NOT NULL, \n\tdestinatarios_email JSONB, \n\twebhook_url VARCHAR(500), \n\tstorage_path VARCHAR(500), \n\ttemplate_id VARCHAR(100), \n\ttemplate_config JSONB, \n\tcustom_query TEXT, \n\tfiltros JSONB, \n\tordenacao JSONB, \n\tagrupamento JSONB, \n\tlogo_url VARCHAR(500), \n\theader_text TEXT, \n\tfooter_text TEXT, \n\tshow_charts BOOLEAN, \n\tshow_summary BOOLEAN, \n\tpaper_size VARCHAR(20), \n\torientation VARCHAR(20), \n\tproxima_execucao_at TIMESTAMP WITHOUT TIME ZONE, \n\tultima_execucao_at TIMESTAMP WITHOUT TIME ZONE, \n\tultima_execucao_status VARCHAR(50), \n\tultima_execucao_erro TEXT, \n\ttotal_execucoes INTEGER, \n\ttotal_erros INTEGER, \n\tultimo_arquivo_url VARCHAR(500), \n\tultimo_arquivo_tamanho INTEGER, \n\tultimo_arquivo_hash VARCHAR(64), \n\tnotificar_sucesso BOOLEAN, \n\tnotificar_erro BOOLEAN, \n\tnotificar_email VARCHAR(255), \n\ttags JSONB, \n\textra_metadata JSONB, \n\tcreated_by UUID, \n\tupdated_by UUID, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE, \n\tPRIMARY KEY (id)\n)",
"CREATE TABLE IF NOT EXISTS payroll_integrations (\n\tid UUID NOT NULL, \n\tcondominio_id UUID NOT NULL, \n\tname VARCHAR(100) NOT NULL, \n\tdescription TEXT, \n\tintegration_type VARCHAR(30) NOT NULL, \n\tendpoint_url VARCHAR(500), \n\tapi_version VARCHAR(20), \n\tauth_type VARCHAR(30), \n\tcredentials JSONB, \n\tesocial_config JSONB, \n\tfield_mapping JSONB, \n\trubrica_mapping JSONB, \n\tsync_config JSONB, \n\tstatus VARCHAR(20) NOT NULL, \n\tlast_sync_at TIMESTAMP WITHOUT TIME ZONE, \n\tlast_sync_status VARCHAR(20), \n\tlast_sync_message TEXT, \n\tlast_sync_records INTEGER, \n\ttotal_syncs INTEGER, \n\tsuccessful_syncs INTEGER, \n\tfailed_syncs INTEGER, \n\twebhook_url VARCHAR(500), \n\twebhook_secret VARCHAR(200), \n\twebhook_events JSONB, \n\terror_log JSONB, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE, \n\tcreated_by UUID, \n\tativo BOOLEAN NOT NULL, \n\tPRIMARY KEY (id)\n)",
"CREATE TABLE IF NOT EXISTS payroll_exports (\n\tid UUID NOT NULL, \n\tcondominio_id UUID NOT NULL, \n\tperiod_id UUID, \n\tintegration_id UUID, \n\texport_code VARCHAR(50) NOT NULL, \n\tname VARCHAR(200) NOT NULL, \n\tdescription TEXT, \n\texport_format VARCHAR(30) NOT NULL, \n\texport_type VARCHAR(50), \n\tscope JSONB, \n\tfile_config JSONB, \n\tfile_name VARCHAR(255), \n\tfile_path VARCHAR(500), \n\tfile_size INTEGER, \n\tfile_hash VARCHAR(64), \n\tstatus VARCHAR(20) NOT NULL, \n\tstarted_at TIMESTAMP WITHOUT TIME ZONE, \n\tcompleted_at TIMESTAMP WITHOUT TIME ZONE, \n\tprocessing_time_ms INTEGER, \n\ttotal_records INTEGER, \n\tprocessed_records INTEGER, \n\tsuccess_records INTEGER, \n\terror_records INTEGER, \n\twarning_records INTEGER, \n\ttransmission_id VARCHAR(100), \n\ttransmission_date TIMESTAMP WITHOUT TIME ZONE, \n\treceipt_number VARCHAR(100), \n\treceipt_date TIMESTAMP WITHOUT TIME ZONE, \n\terrors JSONB, \n\twarnings JSONB, \n\tvalidation_results JSONB, \n\tdownload_url VARCHAR(500), \n\tdownload_expires_at TIMESTAMP WITHOUT TIME ZONE, \n\tdownload_count INTEGER, \n\tretry_count INTEGER, \n\tmax_retries INTEGER, \n\tlast_error TEXT, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE, \n\tcreated_by UUID, \n\tativo BOOLEAN NOT NULL, \n\tPRIMARY KEY (id)\n)",
"CREATE TABLE IF NOT EXISTS simples_nacional_configs (\n\tid UUID NOT NULL, \n\tcondominio_id UUID NOT NULL, \n\tanexo VARCHAR(10) NOT NULL, \n\tfaixa VARCHAR(10), \n\tfaturamento_12_meses NUMERIC(15, 2) NOT NULL, \n\tlimite_sublimite NUMERIC(15, 2), \n\taliquota_nominal NUMERIC(8, 4) NOT NULL, \n\taliquota_efetiva NUMERIC(8, 4), \n\tparcela_deduzir NUMERIC(15, 2), \n\treparticao JSONB, \n\tfolha_pagamento_12_meses NUMERIC(15, 2), \n\tfator_r NUMERIC(8, 4), \n\tcompetencia VARCHAR(7) NOT NULL, \n\tvalid_from DATE NOT NULL, \n\tvalid_until DATE, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE, \n\tactive BOOLEAN NOT NULL, \n\tPRIMARY KEY (id)\n)",
"CREATE TABLE IF NOT EXISTS sped_registros (\n\tid UUID NOT NULL, \n\tsped_file_id UUID NOT NULL, \n\tbloco VARCHAR(1) NOT NULL, \n\tregistro VARCHAR(10) NOT NULL, \n\tlinha INTEGER NOT NULL, \n\tconteudo TEXT NOT NULL, \n\tcampos JSONB, \n\tdocumento_tipo VARCHAR(20), \n\tdocumento_id UUID, \n\tvalido BOOLEAN, \n\terro VARCHAR(255), \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tPRIMARY KEY (id)\n)",
"CREATE TABLE IF NOT EXISTS tax_configurations (\n\tid UUID NOT NULL, \n\tcondominio_id UUID NOT NULL, \n\tname VARCHAR(100) NOT NULL, \n\tdescription TEXT, \n\ttax_type VARCHAR(30) NOT NULL, \n\ttax_regime VARCHAR(30) NOT NULL, \n\tcalculation_type VARCHAR(30) NOT NULL, \n\trate NUMERIC(8, 4), \n\tfixed_value NUMERIC(15, 2), \n\tbase_reduction NUMERIC(8, 4), \n\tcredit_rate NUMERIC(8, 4), \n\ticms_origin VARCHAR(1), \n\ticms_cst VARCHAR(3), \n\ticms_csosn VARCHAR(3), \n\ticms_modbc VARCHAR(1), \n\ticms_mva NUMERIC(8, 4), \n\tpis_cofins_regime VARCHAR(20), \n\tpis_cst VARCHAR(2), \n\tcofins_cst VARCHAR(2), \n\tipi_cst VARCHAR(2), \n\tipi_classe_enquadramento VARCHAR(5), \n\tiss_codigo_servico VARCHAR(20), \n\tiss_local_prestacao VARCHAR(20), \n\thas_retention BOOLEAN, \n\tretention_rate NUMERIC(8, 4), \n\tretention_minimum NUMERIC(15, 2), \n\tvalid_from DATE NOT NULL, \n\tvalid_until DATE, \n\tstatus VARCHAR(20) NOT NULL, \n\tspecial_rules JSONB, \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE, \n\tcreated_by UUID, \n\tactive BOOLEAN NOT NULL, \n\tPRIMARY KEY (id)\n)",
"CREATE TABLE IF NOT EXISTS tax_tables (\n\tid UUID NOT NULL, \n\tcondominio_id UUID NOT NULL, \n\tname VARCHAR(100) NOT NULL, \n\ttax_type VARCHAR(30) NOT NULL, \n\tyear VARCHAR(4) NOT NULL, \n\tvalid_from DATE NOT NULL, \n\tvalid_until DATE, \n\tbrackets JSONB NOT NULL, \n\tdependent_deduction NUMERIC(15, 2), \n\tceiling NUMERIC(15, 2), \n\tfloor NUMERIC(15, 2), \n\tcreated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITHOUT TIME ZONE, \n\tactive BOOLEAN NOT NULL, \n\tPRIMARY KEY (id)\n)",
"ALTER TABLE \"codigos_servico\" ADD COLUMN IF NOT EXISTS \"subitem\" VARCHAR(10)",
"ALTER TABLE \"codigos_servico\" ADD COLUMN IF NOT EXISTS \"aliquota_minima\" NUMERIC(8, 4)",
"ALTER TABLE \"codigos_servico\" ADD COLUMN IF NOT EXISTS \"aliquota_maxima\" NUMERIC(8, 4)",
"ALTER TABLE \"codigos_servico\" ADD COLUMN IF NOT EXISTS \"iss_retido_obrigatorio\" BOOLEAN",
"ALTER TABLE \"codigos_servico\" ADD COLUMN IF NOT EXISTS \"local_tributacao\" VARCHAR(20)",
"ALTER TABLE \"codigos_servico\" ADD COLUMN IF NOT EXISTS \"permite_deducao\" BOOLEAN",
"ALTER TABLE \"codigos_servico\" ADD COLUMN IF NOT EXISTS \"exige_obra\" BOOLEAN",
"ALTER TABLE \"codigos_servico\" ADD COLUMN IF NOT EXISTS \"exige_retencoes_federais\" BOOLEAN",
"ALTER TABLE \"codigos_servico\" ADD COLUMN IF NOT EXISTS \"cnaes_relacionados\" JSONB",
"ALTER TABLE \"codigos_servico\" ADD COLUMN IF NOT EXISTS \"created_at\" TIMESTAMP WITHOUT TIME ZONE NOT NULL",
"ALTER TABLE \"codigos_servico\" ADD COLUMN IF NOT EXISTS \"updated_at\" TIMESTAMP WITHOUT TIME ZONE",
"ALTER TABLE \"fin_stock_inventories\" ADD COLUMN IF NOT EXISTS \"number\" VARCHAR(20) NOT NULL",
"ALTER TABLE \"fin_stock_inventories\" ADD COLUMN IF NOT EXISTS \"planned_date\" DATE",
"ALTER TABLE \"fin_stock_inventories\" ADD COLUMN IF NOT EXISTS \"start_date\" TIMESTAMP WITHOUT TIME ZONE",
"ALTER TABLE \"fin_stock_inventories\" ADD COLUMN IF NOT EXISTS \"end_date\" TIMESTAMP WITHOUT TIME ZONE",
"ALTER TABLE \"fin_stock_inventories\" ADD COLUMN IF NOT EXISTS \"deadline\" TIMESTAMP WITHOUT TIME ZONE",
"ALTER TABLE \"fin_stock_inventories\" ADD COLUMN IF NOT EXISTS \"filter_categories\" JSONB",
"ALTER TABLE \"fin_stock_inventories\" ADD COLUMN IF NOT EXISTS \"filter_locations\" JSONB",
"ALTER TABLE \"fin_stock_inventories\" ADD COLUMN IF NOT EXISTS \"filter_abc_class\" JSONB",
"ALTER TABLE \"fin_stock_inventories\" ADD COLUMN IF NOT EXISTS \"filter_products\" JSONB",
"ALTER TABLE \"fin_stock_inventories\" ADD COLUMN IF NOT EXISTS \"verified_items\" INTEGER",
"ALTER TABLE \"fin_stock_inventories\" ADD COLUMN IF NOT EXISTS \"expected_value\" NUMERIC(15, 2)",
"ALTER TABLE \"fin_stock_inventories\" ADD COLUMN IF NOT EXISTS \"counted_value\" NUMERIC(15, 2)",
"ALTER TABLE \"fin_stock_inventories\" ADD COLUMN IF NOT EXISTS \"difference_value\" NUMERIC(15, 2)",
"ALTER TABLE \"fin_stock_inventories\" ADD COLUMN IF NOT EXISTS \"adjustment_value\" NUMERIC(15, 2)",
"ALTER TABLE \"fin_stock_inventories\" ADD COLUMN IF NOT EXISTS \"expected_quantity\" NUMERIC(15, 4)",
"ALTER TABLE \"fin_stock_inventories\" ADD COLUMN IF NOT EXISTS \"counted_quantity\" NUMERIC(15, 4)",
"ALTER TABLE \"fin_stock_inventories\" ADD COLUMN IF NOT EXISTS \"difference_quantity\" NUMERIC(15, 4)",
"ALTER TABLE \"fin_stock_inventories\" ADD COLUMN IF NOT EXISTS \"accuracy_rate\" NUMERIC(5, 2)",
"ALTER TABLE \"fin_stock_inventories\" ADD COLUMN IF NOT EXISTS \"hit_rate\" NUMERIC(5, 2)",
"ALTER TABLE \"fin_stock_inventories\" ADD COLUMN IF NOT EXISTS \"auto_adjust\" BOOLEAN",
"ALTER TABLE \"fin_stock_inventories\" ADD COLUMN IF NOT EXISTS \"internal_notes\" TEXT",
"ALTER TABLE \"fin_stock_inventories\" ADD COLUMN IF NOT EXISTS \"attachments\" JSONB",
"ALTER TABLE \"fin_stock_inventories\" ADD COLUMN IF NOT EXISTS \"extra_data\" JSONB",
"ALTER TABLE \"fin_stock_inventories\" ADD COLUMN IF NOT EXISTS \"ativo\" BOOLEAN NOT NULL",
"ALTER TABLE \"fin_stock_inventory_items\" ADD COLUMN IF NOT EXISTS \"expiry_date\" DATE",
"ALTER TABLE \"fin_stock_inventory_items\" ADD COLUMN IF NOT EXISTS \"aisle\" VARCHAR(10)",
"ALTER TABLE \"fin_stock_inventory_items\" ADD COLUMN IF NOT EXISTS \"rack\" VARCHAR(10)",
"ALTER TABLE \"fin_stock_inventory_items\" ADD COLUMN IF NOT EXISTS \"shelf\" VARCHAR(10)",
"ALTER TABLE \"fin_stock_inventory_items\" ADD COLUMN IF NOT EXISTS \"bin_loc\" VARCHAR(10)",
"ALTER TABLE \"fin_stock_inventory_items\" ADD COLUMN IF NOT EXISTS \"expected_quantity\" NUMERIC(15, 4)",
"ALTER TABLE \"fin_stock_inventory_items\" ADD COLUMN IF NOT EXISTS \"recount_quantity\" NUMERIC(15, 4)",
"ALTER TABLE \"fin_stock_inventory_items\" ADD COLUMN IF NOT EXISTS \"difference_quantity\" NUMERIC(15, 4)",
"ALTER TABLE \"fin_stock_inventory_items\" ADD COLUMN IF NOT EXISTS \"expected_value\" NUMERIC(15, 2)",
"ALTER TABLE \"fin_stock_inventory_items\" ADD COLUMN IF NOT EXISTS \"difference_value\" NUMERIC(15, 2)",
"ALTER TABLE \"fin_stock_inventory_items\" ADD COLUMN IF NOT EXISTS \"recounted_at\" TIMESTAMP WITHOUT TIME ZONE",
"ALTER TABLE \"fin_stock_inventory_items\" ADD COLUMN IF NOT EXISTS \"recounted_by\" UUID",
"ALTER TABLE \"fin_stock_inventory_items\" ADD COLUMN IF NOT EXISTS \"verified_at\" TIMESTAMP WITHOUT TIME ZONE",
"ALTER TABLE \"fin_stock_inventory_items\" ADD COLUMN IF NOT EXISTS \"verified_by\" UUID",
"ALTER TABLE \"fin_stock_inventory_items\" ADD COLUMN IF NOT EXISTS \"adjusted_at\" TIMESTAMP WITHOUT TIME ZONE",
"ALTER TABLE \"fin_stock_inventory_items\" ADD COLUMN IF NOT EXISTS \"adjusted_by\" UUID",
"ALTER TABLE \"fin_stock_inventory_items\" ADD COLUMN IF NOT EXISTS \"ativo\" BOOLEAN NOT NULL",
"ALTER TABLE \"fin_stock_movements\" ADD COLUMN IF NOT EXISTS \"number\" VARCHAR(20) NOT NULL",
"ALTER TABLE \"fin_stock_movements\" ADD COLUMN IF NOT EXISTS \"reason\" VARCHAR(30) NOT NULL",
"ALTER TABLE \"fin_stock_movements\" ADD COLUMN IF NOT EXISTS \"expiry_date\" DATE",
"ALTER TABLE \"fin_stock_movements\" ADD COLUMN IF NOT EXISTS \"source_location\" VARCHAR(50)",
"ALTER TABLE \"fin_stock_movements\" ADD COLUMN IF NOT EXISTS \"source_aisle\" VARCHAR(10)",
"ALTER TABLE \"fin_stock_movements\" ADD COLUMN IF NOT EXISTS \"source_rack\" VARCHAR(10)",
"ALTER TABLE \"fin_stock_movements\" ADD COLUMN IF NOT EXISTS \"source_shelf\" VARCHAR(10)",
"ALTER TABLE \"fin_stock_movements\" ADD COLUMN IF NOT EXISTS \"source_bin\" VARCHAR(10)",
"ALTER TABLE \"fin_stock_movements\" ADD COLUMN IF NOT EXISTS \"dest_location\" VARCHAR(50)",
"ALTER TABLE \"fin_stock_movements\" ADD COLUMN IF NOT EXISTS \"dest_aisle\" VARCHAR(10)",
"ALTER TABLE \"fin_stock_movements\" ADD COLUMN IF NOT EXISTS \"dest_rack\" VARCHAR(10)",
"ALTER TABLE \"fin_stock_movements\" ADD COLUMN IF NOT EXISTS \"dest_shelf\" VARCHAR(10)",
"ALTER TABLE \"fin_stock_movements\" ADD COLUMN IF NOT EXISTS \"dest_bin\" VARCHAR(10)",
"ALTER TABLE \"fin_stock_movements\" ADD COLUMN IF NOT EXISTS \"reference_type\" VARCHAR(50)",
"ALTER TABLE \"fin_stock_movements\" ADD COLUMN IF NOT EXISTS \"reference_id\" UUID",
"ALTER TABLE \"fin_stock_movements\" ADD COLUMN IF NOT EXISTS \"reference_number\" VARCHAR(50)",
"ALTER TABLE \"fin_stock_movements\" ADD COLUMN IF NOT EXISTS \"invoice_number\" VARCHAR(50)",
"ALTER TABLE \"fin_stock_movements\" ADD COLUMN IF NOT EXISTS \"invoice_series\" VARCHAR(10)",
"ALTER TABLE \"fin_stock_movements\" ADD COLUMN IF NOT EXISTS \"invoice_key\" VARCHAR(50)",
"ALTER TABLE \"fin_stock_movements\" ADD COLUMN IF NOT EXISTS \"supplier_id\" UUID",
"ALTER TABLE \"fin_stock_movements\" ADD COLUMN IF NOT EXISTS \"customer_id\" UUID",
"ALTER TABLE \"fin_stock_movements\" ADD COLUMN IF NOT EXISTS \"requisition_id\" UUID",
"ALTER TABLE \"fin_stock_movements\" ADD COLUMN IF NOT EXISTS \"requisition_number\" VARCHAR(50)",
"ALTER TABLE \"fin_stock_movements\" ADD COLUMN IF NOT EXISTS \"reversal_of\" UUID",
"ALTER TABLE \"fin_stock_movements\" ADD COLUMN IF NOT EXISTS \"reversed_by\" UUID",
"ALTER TABLE \"fin_stock_movements\" ADD COLUMN IF NOT EXISTS \"internal_notes\" TEXT",
"ALTER TABLE \"fin_stock_movements\" ADD COLUMN IF NOT EXISTS \"attachments\" JSONB",
"ALTER TABLE \"fin_stock_movements\" ADD COLUMN IF NOT EXISTS \"extra_data\" JSONB",
"ALTER TABLE \"fin_stock_movements\" ADD COLUMN IF NOT EXISTS \"confirmed_by\" UUID",
"ALTER TABLE \"fin_stock_movements\" ADD COLUMN IF NOT EXISTS \"ativo\" BOOLEAN NOT NULL",
"ALTER TABLE \"fin_stock_reservations\" ADD COLUMN IF NOT EXISTS \"number\" VARCHAR(20) NOT NULL",
"ALTER TABLE \"fin_stock_reservations\" ADD COLUMN IF NOT EXISTS \"description\" VARCHAR(200)",
"ALTER TABLE \"fin_stock_reservations\" ADD COLUMN IF NOT EXISTS \"batch_number\" VARCHAR(50)",
"ALTER TABLE \"fin_stock_reservations\" ADD COLUMN IF NOT EXISTS \"quantity_requested\" NUMERIC(15, 4) NOT NULL",
"ALTER TABLE \"fin_stock_reservations\" ADD COLUMN IF NOT EXISTS \"quantity_pending\" NUMERIC(15, 4)",
"ALTER TABLE \"fin_stock_reservations\" ADD COLUMN IF NOT EXISTS \"required_date\" TIMESTAMP WITHOUT TIME ZONE",
"ALTER TABLE \"fin_stock_reservations\" ADD COLUMN IF NOT EXISTS \"reference_type\" VARCHAR(50)",
"ALTER TABLE \"fin_stock_reservations\" ADD COLUMN IF NOT EXISTS \"reference_id\" UUID",
"ALTER TABLE \"fin_stock_reservations\" ADD COLUMN IF NOT EXISTS \"reference_number\" VARCHAR(50)",
"ALTER TABLE \"fin_stock_reservations\" ADD COLUMN IF NOT EXISTS \"requester_id\" UUID",
"ALTER TABLE \"fin_stock_reservations\" ADD COLUMN IF NOT EXISTS \"requester_name\" VARCHAR(100)",
"ALTER TABLE \"fin_stock_reservations\" ADD COLUMN IF NOT EXISTS \"requires_approval\" BOOLEAN",
"ALTER TABLE \"fin_stock_reservations\" ADD COLUMN IF NOT EXISTS \"approved_by\" UUID",
"ALTER TABLE \"fin_stock_reservations\" ADD COLUMN IF NOT EXISTS \"approved_at\" TIMESTAMP WITHOUT TIME ZONE",
"ALTER TABLE \"fin_stock_reservations\" ADD COLUMN IF NOT EXISTS \"approval_notes\" TEXT",
"ALTER TABLE \"fin_stock_reservations\" ADD COLUMN IF NOT EXISTS \"released_by\" UUID",
"ALTER TABLE \"fin_stock_reservations\" ADD COLUMN IF NOT EXISTS \"release_notes\" TEXT",
"ALTER TABLE \"fin_stock_reservations\" ADD COLUMN IF NOT EXISTS \"cancelled_by\" UUID",
"ALTER TABLE \"fin_stock_reservations\" ADD COLUMN IF NOT EXISTS \"auto_expire\" BOOLEAN",
"ALTER TABLE \"fin_stock_reservations\" ADD COLUMN IF NOT EXISTS \"allow_partial\" BOOLEAN",
"ALTER TABLE \"fin_stock_reservations\" ADD COLUMN IF NOT EXISTS \"internal_notes\" TEXT",
"ALTER TABLE \"fin_stock_reservations\" ADD COLUMN IF NOT EXISTS \"extra_data\" JSONB",
"ALTER TABLE \"fin_stock_reservations\" ADD COLUMN IF NOT EXISTS \"ativo\" BOOLEAN NOT NULL",
"ALTER TABLE \"goods_receipt_items\" ADD COLUMN IF NOT EXISTS \"updated_at\" TIMESTAMP WITHOUT TIME ZONE",
"ALTER TABLE \"goods_receipts\" ADD COLUMN IF NOT EXISTS \"approval_notes\" TEXT",
"ALTER TABLE \"goods_receipts\" ADD COLUMN IF NOT EXISTS \"rejected_at\" TIMESTAMP WITHOUT TIME ZONE",
"ALTER TABLE \"goods_receipts\" ADD COLUMN IF NOT EXISTS \"rejected_by\" UUID",
"ALTER TABLE \"goods_receipts\" ADD COLUMN IF NOT EXISTS \"internal_notes\" TEXT",
"ALTER TABLE \"goods_receipts\" ADD COLUMN IF NOT EXISTS \"receiver_signature\" TEXT",
"ALTER TABLE \"payable_categories\" ADD COLUMN IF NOT EXISTS \"created_by\" UUID",
"ALTER TABLE \"payment_methods\" ADD COLUMN IF NOT EXISTS \"created_by\" UUID",
"ALTER TABLE \"products\" ADD COLUMN IF NOT EXISTS \"technical_specs\" TEXT",
"ALTER TABLE \"products\" ADD COLUMN IF NOT EXISTS \"conversion_factor\" NUMERIC(10, 4)",
"ALTER TABLE \"products\" ADD COLUMN IF NOT EXISTS \"min_stock\" NUMERIC(10, 2)",
"ALTER TABLE \"products\" ADD COLUMN IF NOT EXISTS \"max_stock\" NUMERIC(10, 2)",
"ALTER TABLE \"products\" ADD COLUMN IF NOT EXISTS \"cest\" VARCHAR(10)",
"ALTER TABLE \"products\" ADD COLUMN IF NOT EXISTS \"cfop_default\" VARCHAR(10)",
"ALTER TABLE \"products\" ADD COLUMN IF NOT EXISTS \"preferred_supplier_id\" UUID",
"ALTER TABLE \"products\" ADD COLUMN IF NOT EXISTS \"thumbnail_url\" VARCHAR(500)",
"ALTER TABLE \"products\" ADD COLUMN IF NOT EXISTS \"documents\" JSONB",
"ALTER TABLE \"products\" ADD COLUMN IF NOT EXISTS \"attributes\" JSONB",
"ALTER TABLE \"products\" ADD COLUMN IF NOT EXISTS \"brand\" VARCHAR(100)",
"ALTER TABLE \"products\" ADD COLUMN IF NOT EXISTS \"manufacturer\" VARCHAR(100)",
"ALTER TABLE \"products\" ADD COLUMN IF NOT EXISTS \"model\" VARCHAR(100)",
"ALTER TABLE \"products\" ADD COLUMN IF NOT EXISTS \"internal_notes\" TEXT",
"ALTER TABLE \"products\" ADD COLUMN IF NOT EXISTS \"blocked_reason\" TEXT",
"ALTER TABLE \"products\" ADD COLUMN IF NOT EXISTS \"total_purchases\" VARCHAR(10)",
"ALTER TABLE \"products\" ADD COLUMN IF NOT EXISTS \"last_purchase_at\" TIMESTAMP WITHOUT TIME ZONE",
"ALTER TABLE \"purchase_approvals\" ADD COLUMN IF NOT EXISTS \"info_requested_at\" TIMESTAMP WITHOUT TIME ZONE",
"ALTER TABLE \"purchase_approvals\" ADD COLUMN IF NOT EXISTS \"info_provided_at\" TIMESTAMP WITHOUT TIME ZONE",
"ALTER TABLE \"purchase_approvals\" ADD COLUMN IF NOT EXISTS \"notification_sent_at\" TIMESTAMP WITHOUT TIME ZONE",
"ALTER TABLE \"purchase_approvals\" ADD COLUMN IF NOT EXISTS \"last_reminder_at\" TIMESTAMP WITHOUT TIME ZONE",
"ALTER TABLE \"purchase_approvals\" ADD COLUMN IF NOT EXISTS \"attachments\" JSONB",
"ALTER TABLE \"purchase_approvals\" ADD COLUMN IF NOT EXISTS \"created_by\" UUID",
"ALTER TABLE \"purchase_order_items\" ADD COLUMN IF NOT EXISTS \"updated_at\" TIMESTAMP WITHOUT TIME ZONE",
"ALTER TABLE \"purchase_quotation_items\" ADD COLUMN IF NOT EXISTS \"supplier_description\" VARCHAR(500)",
"ALTER TABLE \"purchase_quotation_items\" ADD COLUMN IF NOT EXISTS \"quantity_requested\" NUMERIC(10, 2) NOT NULL",
"ALTER TABLE \"purchase_quotation_items\" ADD COLUMN IF NOT EXISTS \"quantity_offered\" NUMERIC(10, 2)",
"ALTER TABLE \"purchase_quotation_items\" ADD COLUMN IF NOT EXISTS \"min_quantity\" NUMERIC(10, 2)",
"ALTER TABLE \"purchase_quotation_items\" ADD COLUMN IF NOT EXISTS \"discount_percentage\" NUMERIC(5, 2)",
"ALTER TABLE \"purchase_quotation_items\" ADD COLUMN IF NOT EXISTS \"discount_amount\" NUMERIC(15, 2)",
"ALTER TABLE \"purchase_quotation_items\" ADD COLUMN IF NOT EXISTS \"availability\" VARCHAR(50)",
"ALTER TABLE \"purchase_quotation_items\" ADD COLUMN IF NOT EXISTS \"technical_specs\" TEXT",
"ALTER TABLE \"purchase_quotation_items\" ADD COLUMN IF NOT EXISTS \"meets_specs\" BOOLEAN",
"ALTER TABLE \"purchase_quotation_items\" ADD COLUMN IF NOT EXISTS \"evaluation_notes\" TEXT",
"ALTER TABLE \"purchase_quotation_items\" ADD COLUMN IF NOT EXISTS \"updated_at\" TIMESTAMP WITHOUT TIME ZONE",
"ALTER TABLE \"purchase_quotations\" ADD COLUMN IF NOT EXISTS \"reference\" VARCHAR(50)",
"ALTER TABLE \"purchase_quotations\" ADD COLUMN IF NOT EXISTS \"request_date\" DATE NOT NULL",
"ALTER TABLE \"purchase_quotations\" ADD COLUMN IF NOT EXISTS \"sent_date\" TIMESTAMP WITHOUT TIME ZONE",
"ALTER TABLE \"purchase_quotations\" ADD COLUMN IF NOT EXISTS \"received_date\" TIMESTAMP WITHOUT TIME ZONE",
"ALTER TABLE \"purchase_quotations\" ADD COLUMN IF NOT EXISTS \"validity_date\" DATE",
"ALTER TABLE \"purchase_quotations\" ADD COLUMN IF NOT EXISTS \"expected_delivery_date\" DATE",
"ALTER TABLE \"purchase_quotations\" ADD COLUMN IF NOT EXISTS \"payment_installments\" INTEGER",
"ALTER TABLE \"purchase_quotations\" ADD COLUMN IF NOT EXISTS \"internal_notes\" TEXT",
"ALTER TABLE \"purchase_quotations\" ADD COLUMN IF NOT EXISTS \"rejected_at\" TIMESTAMP WITHOUT TIME ZONE",
"ALTER TABLE \"purchase_quotations\" ADD COLUMN IF NOT EXISTS \"rejected_by\" UUID",
"ALTER TABLE \"purchase_quotations\" ADD COLUMN IF NOT EXISTS \"selection_justification\" TEXT",
"ALTER TABLE \"purchase_quotations\" ADD COLUMN IF NOT EXISTS \"comparison_notes\" TEXT",
"ALTER TABLE \"purchase_quotations\" ADD COLUMN IF NOT EXISTS \"is_best_price\" BOOLEAN",
"ALTER TABLE \"purchase_quotations\" ADD COLUMN IF NOT EXISTS \"is_best_delivery\" BOOLEAN",
"ALTER TABLE \"purchase_quotations\" ADD COLUMN IF NOT EXISTS \"is_best_overall\" BOOLEAN",
"ALTER TABLE \"purchase_requisition_items\" ADD COLUMN IF NOT EXISTS \"quantity_requested\" NUMERIC(10, 2) NOT NULL",
"ALTER TABLE \"purchase_requisition_items\" ADD COLUMN IF NOT EXISTS \"quantity_received\" NUMERIC(10, 2)",
"ALTER TABLE \"purchase_requisition_items\" ADD COLUMN IF NOT EXISTS \"estimated_unit_price\" NUMERIC(15, 2)",
"ALTER TABLE \"purchase_requisition_items\" ADD COLUMN IF NOT EXISTS \"approved_unit_price\" NUMERIC(15, 2)",
"ALTER TABLE \"purchase_requisition_items\" ADD COLUMN IF NOT EXISTS \"actual_unit_price\" NUMERIC(15, 2)",
"ALTER TABLE \"purchase_requisition_items\" ADD COLUMN IF NOT EXISTS \"updated_at\" TIMESTAMP WITHOUT TIME ZONE",
"ALTER TABLE \"purchase_requisitions\" ADD COLUMN IF NOT EXISTS \"revision\" INTEGER",
"ALTER TABLE \"purchase_requisitions\" ADD COLUMN IF NOT EXISTS \"title\" VARCHAR(200) NOT NULL",
"ALTER TABLE \"purchase_requisitions\" ADD COLUMN IF NOT EXISTS \"request_date\" DATE NOT NULL",
"ALTER TABLE \"purchase_requisitions\" ADD COLUMN IF NOT EXISTS \"needed_by_date\" DATE",
"ALTER TABLE \"purchase_requisitions\" ADD COLUMN IF NOT EXISTS \"approved_at\" TIMESTAMP WITHOUT TIME ZONE",
"ALTER TABLE \"purchase_requisitions\" ADD COLUMN IF NOT EXISTS \"approved_budget\" NUMERIC(15, 2)",
"ALTER TABLE \"purchase_requisitions\" ADD COLUMN IF NOT EXISTS \"actual_total\" NUMERIC(15, 2)",
"ALTER TABLE \"purchase_requisitions\" ADD COLUMN IF NOT EXISTS \"min_quotations\" INTEGER",
"ALTER TABLE \"purchase_requisitions\" ADD COLUMN IF NOT EXISTS \"delivery_address\" TEXT",
"ALTER TABLE \"purchase_requisitions\" ADD COLUMN IF NOT EXISTS \"delivery_contact\" VARCHAR(100)",
"ALTER TABLE \"purchase_requisitions\" ADD COLUMN IF NOT EXISTS \"delivery_phone\" VARCHAR(20)",
"ALTER TABLE \"purchase_requisitions\" ADD COLUMN IF NOT EXISTS \"delivery_instructions\" TEXT",
"ALTER TABLE \"purchase_requisitions\" ADD COLUMN IF NOT EXISTS \"suggested_supplier_id\" UUID",
"ALTER TABLE \"purchase_requisitions\" ADD COLUMN IF NOT EXISTS \"supplier_justification\" TEXT",
"ALTER TABLE \"purchase_requisitions\" ADD COLUMN IF NOT EXISTS \"internal_notes\" TEXT",
"ALTER TABLE \"purchase_requisitions\" ADD COLUMN IF NOT EXISTS \"rejected_at\" TIMESTAMP WITHOUT TIME ZONE",
"ALTER TABLE \"purchase_requisitions\" ADD COLUMN IF NOT EXISTS \"cancelled_at\" TIMESTAMP WITHOUT TIME ZONE",
"ALTER TABLE \"purchase_requisitions\" ADD COLUMN IF NOT EXISTS \"cancelled_by\" UUID",
"ALTER TABLE \"purchase_requisitions\" ADD COLUMN IF NOT EXISTS \"approval_history\" JSONB",
"ALTER TABLE \"receivable_categories\" ADD COLUMN IF NOT EXISTS \"apply_interest\" BOOLEAN",
"ALTER TABLE \"receivable_categories\" ADD COLUMN IF NOT EXISTS \"interest_rate\" VARCHAR(10)",
"ALTER TABLE \"receivable_categories\" ADD COLUMN IF NOT EXISTS \"apply_penalty\" BOOLEAN",
"ALTER TABLE \"receivable_categories\" ADD COLUMN IF NOT EXISTS \"penalty_rate\" VARCHAR(10)",
"ALTER TABLE \"simples_nacional_das\" ADD COLUMN IF NOT EXISTS \"competencia\" VARCHAR(7) NOT NULL",
"ALTER TABLE \"simples_nacional_das\" ADD COLUMN IF NOT EXISTS \"ano\" INTEGER NOT NULL",
"ALTER TABLE \"simples_nacional_das\" ADD COLUMN IF NOT EXISTS \"mes\" INTEGER NOT NULL",
"ALTER TABLE \"simples_nacional_das\" ADD COLUMN IF NOT EXISTS \"fator_r\" NUMERIC(8, 4)",
"ALTER TABLE \"simples_nacional_das\" ADD COLUMN IF NOT EXISTS \"folha_pagamento_12_meses\" NUMERIC(15, 2)",
"ALTER TABLE \"simples_nacional_das\" ADD COLUMN IF NOT EXISTS \"valor_das\" NUMERIC(15, 2) NOT NULL",
"ALTER TABLE \"simples_nacional_das\" ADD COLUMN IF NOT EXISTS \"reparticao\" JSONB",
"ALTER TABLE \"simples_nacional_das\" ADD COLUMN IF NOT EXISTS \"valor_irpj\" NUMERIC(15, 2)",
"ALTER TABLE \"simples_nacional_das\" ADD COLUMN IF NOT EXISTS \"valor_csll\" NUMERIC(15, 2)",
"ALTER TABLE \"simples_nacional_das\" ADD COLUMN IF NOT EXISTS \"valor_cofins\" NUMERIC(15, 2)",
"ALTER TABLE \"simples_nacional_das\" ADD COLUMN IF NOT EXISTS \"valor_pis\" NUMERIC(15, 2)",
"ALTER TABLE \"simples_nacional_das\" ADD COLUMN IF NOT EXISTS \"valor_cpp\" NUMERIC(15, 2)",
"ALTER TABLE \"simples_nacional_das\" ADD COLUMN IF NOT EXISTS \"valor_icms\" NUMERIC(15, 2)",
"ALTER TABLE \"simples_nacional_das\" ADD COLUMN IF NOT EXISTS \"valor_iss\" NUMERIC(15, 2)",
"ALTER TABLE \"simples_nacional_das\" ADD COLUMN IF NOT EXISTS \"numero_das\" VARCHAR(30)",
"ALTER TABLE \"simples_nacional_das\" ADD COLUMN IF NOT EXISTS \"iss_retido\" BOOLEAN",
"ALTER TABLE \"simples_nacional_das\" ADD COLUMN IF NOT EXISTS \"valor_iss_retido\" NUMERIC(15, 2)",
"ALTER TABLE \"sped_files\" ADD COLUMN IF NOT EXISTS \"versao_layout\" VARCHAR(10) NOT NULL",
"ALTER TABLE \"sped_files\" ADD COLUMN IF NOT EXISTS \"periodo_inicio\" DATE NOT NULL",
"ALTER TABLE \"sped_files\" ADD COLUMN IF NOT EXISTS \"periodo_fim\" DATE NOT NULL",
"ALTER TABLE \"sped_files\" ADD COLUMN IF NOT EXISTS \"data_geracao\" TIMESTAMP WITHOUT TIME ZONE",
"ALTER TABLE \"sped_files\" ADD COLUMN IF NOT EXISTS \"data_validacao\" TIMESTAMP WITHOUT TIME ZONE",
"ALTER TABLE \"sped_files\" ADD COLUMN IF NOT EXISTS \"cnpj\" VARCHAR(14) NOT NULL",
"ALTER TABLE \"sped_files\" ADD COLUMN IF NOT EXISTS \"razao_social\" VARCHAR(150) NOT NULL",
"ALTER TABLE \"sped_files\" ADD COLUMN IF NOT EXISTS \"inscricao_estadual\" VARCHAR(14)",
"ALTER TABLE \"sped_files\" ADD COLUMN IF NOT EXISTS \"uf\" VARCHAR(2)",
"ALTER TABLE \"sped_files\" ADD COLUMN IF NOT EXISTS \"caminho_arquivo\" VARCHAR(500)",
"ALTER TABLE \"sped_files\" ADD COLUMN IF NOT EXISTS \"pva_versao\" VARCHAR(20)",
"ALTER TABLE \"sped_files\" ADD COLUMN IF NOT EXISTS \"pva_resultado\" VARCHAR(20)",
"ALTER TABLE \"sped_files\" ADD COLUMN IF NOT EXISTS \"pva_erros\" INTEGER",
"ALTER TABLE \"sped_files\" ADD COLUMN IF NOT EXISTS \"pva_avisos\" INTEGER",
"ALTER TABLE \"sped_files\" ADD COLUMN IF NOT EXISTS \"pva_log\" TEXT",
"ALTER TABLE \"sped_files\" ADD COLUMN IF NOT EXISTS \"protocolo\" VARCHAR(50)",
"ALTER TABLE \"sped_files\" ADD COLUMN IF NOT EXISTS \"recibo\" VARCHAR(50)",
"ALTER TABLE \"sped_files\" ADD COLUMN IF NOT EXISTS \"codigo_retorno\" VARCHAR(10)",
"ALTER TABLE \"sped_files\" ADD COLUMN IF NOT EXISTS \"mensagem_retorno\" TEXT",
"ALTER TABLE \"sped_files\" ADD COLUMN IF NOT EXISTS \"sped_retificado_id\" UUID",
"ALTER TABLE \"sped_files\" ADD COLUMN IF NOT EXISTS \"nire\" VARCHAR(20)",
"ALTER TABLE \"sped_files\" ADD COLUMN IF NOT EXISTS \"estatisticas\" JSONB",
"ALTER TABLE \"sped_files\" ADD COLUMN IF NOT EXISTS \"valores_resumo\" JSONB",
"ALTER TABLE \"sped_files\" ADD COLUMN IF NOT EXISTS \"created_by\" UUID",
"ALTER TABLE \"suframa_configs\" ADD COLUMN IF NOT EXISTS \"tipo_zona\" VARCHAR(20) NOT NULL",
"ALTER TABLE \"suframa_configs\" ADD COLUMN IF NOT EXISTS \"status\" VARCHAR(20) NOT NULL",
"ALTER TABLE \"suframa_configs\" ADD COLUMN IF NOT EXISTS \"data_inscricao\" DATE",
"ALTER TABLE \"suframa_configs\" ADD COLUMN IF NOT EXISTS \"cnpj\" VARCHAR(14) NOT NULL",
"ALTER TABLE \"suframa_configs\" ADD COLUMN IF NOT EXISTS \"razao_social\" VARCHAR(150) NOT NULL",
"ALTER TABLE \"suframa_configs\" ADD COLUMN IF NOT EXISTS \"nome_fantasia\" VARCHAR(60)",
"ALTER TABLE \"suframa_configs\" ADD COLUMN IF NOT EXISTS \"endereco\" JSONB",
"ALTER TABLE \"suframa_configs\" ADD COLUMN IF NOT EXISTS \"codigo_municipio\" VARCHAR(7)",
"ALTER TABLE \"suframa_configs\" ADD COLUMN IF NOT EXISTS \"municipio_nome\" VARCHAR(100)",
"ALTER TABLE \"suframa_configs\" ADD COLUMN IF NOT EXISTS \"uf\" VARCHAR(2) NOT NULL",
"ALTER TABLE \"suframa_configs\" ADD COLUMN IF NOT EXISTS \"cnaes_habilitados\" JSONB",
"ALTER TABLE \"suframa_configs\" ADD COLUMN IF NOT EXISTS \"beneficio_ipi\" BOOLEAN",
"ALTER TABLE \"suframa_configs\" ADD COLUMN IF NOT EXISTS \"beneficio_icms\" BOOLEAN",
"ALTER TABLE \"suframa_configs\" ADD COLUMN IF NOT EXISTS \"beneficio_pis_cofins\" BOOLEAN",
"ALTER TABLE \"suframa_configs\" ADD COLUMN IF NOT EXISTS \"beneficio_ii\" BOOLEAN",
"ALTER TABLE \"suframa_configs\" ADD COLUMN IF NOT EXISTS \"reducao_icms_interno\" NUMERIC(8, 4)",
"ALTER TABLE \"suframa_configs\" ADD COLUMN IF NOT EXISTS \"reducao_icms_interestadual\" NUMERIC(8, 4)",
"ALTER TABLE \"suframa_configs\" ADD COLUMN IF NOT EXISTS \"credito_presumido_icms\" NUMERIC(8, 4)",
"ALTER TABLE \"suframa_configs\" ADD COLUMN IF NOT EXISTS \"simples_nacional\" BOOLEAN",
"ALTER TABLE \"suframa_configs\" ADD COLUMN IF NOT EXISTS \"simples_anexo\" VARCHAR(5)",
"ALTER TABLE \"suframa_configs\" ADD COLUMN IF NOT EXISTS \"simples_faixa\" VARCHAR(5)",
"ALTER TABLE \"suframa_configs\" ADD COLUMN IF NOT EXISTS \"documentos\" JSONB",
"ALTER TABLE \"suframa_configs\" ADD COLUMN IF NOT EXISTS \"created_by\" UUID",
"ALTER TABLE \"suframa_operacoes\" ADD COLUMN IF NOT EXISTS \"suframa_config_id\" UUID NOT NULL",
"ALTER TABLE \"suframa_operacoes\" ADD COLUMN IF NOT EXISTS \"documento_tipo\" VARCHAR(10) NOT NULL",
"ALTER TABLE \"suframa_operacoes\" ADD COLUMN IF NOT EXISTS \"documento_id\" UUID NOT NULL",
"ALTER TABLE \"suframa_operacoes\" ADD COLUMN IF NOT EXISTS \"chave_acesso\" VARCHAR(44)",
"ALTER TABLE \"suframa_operacoes\" ADD COLUMN IF NOT EXISTS \"numero_documento\" VARCHAR(20)",
"ALTER TABLE \"suframa_operacoes\" ADD COLUMN IF NOT EXISTS \"participante_cnpj\" VARCHAR(14) NOT NULL",
"ALTER TABLE \"suframa_operacoes\" ADD COLUMN IF NOT EXISTS \"participante_suframa\" VARCHAR(20)",
"ALTER TABLE \"suframa_operacoes\" ADD COLUMN IF NOT EXISTS \"participante_razao_social\" VARCHAR(150)",
"ALTER TABLE \"suframa_operacoes\" ADD COLUMN IF NOT EXISTS \"cfop\" VARCHAR(4) NOT NULL",
"ALTER TABLE \"suframa_operacoes\" ADD COLUMN IF NOT EXISTS \"valor_produtos\" NUMERIC(15, 2) NOT NULL",
"ALTER TABLE \"suframa_operacoes\" ADD COLUMN IF NOT EXISTS \"ipi_isento\" BOOLEAN",
"ALTER TABLE \"suframa_operacoes\" ADD COLUMN IF NOT EXISTS \"ipi_economia\" NUMERIC(15, 2)",
"ALTER TABLE \"suframa_operacoes\" ADD COLUMN IF NOT EXISTS \"icms_isento\" BOOLEAN",
"ALTER TABLE \"suframa_operacoes\" ADD COLUMN IF NOT EXISTS \"icms_reducao_percentual\" NUMERIC(8, 4)",
"ALTER TABLE \"suframa_operacoes\" ADD COLUMN IF NOT EXISTS \"icms_economia\" NUMERIC(15, 2)",
"ALTER TABLE \"suframa_operacoes\" ADD COLUMN IF NOT EXISTS \"pis_suspenso\" BOOLEAN",
"ALTER TABLE \"suframa_operacoes\" ADD COLUMN IF NOT EXISTS \"pis_economia\" NUMERIC(15, 2)",
"ALTER TABLE \"suframa_operacoes\" ADD COLUMN IF NOT EXISTS \"cofins_suspenso\" BOOLEAN",
"ALTER TABLE \"suframa_operacoes\" ADD COLUMN IF NOT EXISTS \"cofins_economia\" NUMERIC(15, 2)",
"ALTER TABLE \"suframa_operacoes\" ADD COLUMN IF NOT EXISTS \"total_economia\" NUMERIC(15, 2)",
"ALTER TABLE \"suframa_operacoes\" ADD COLUMN IF NOT EXISTS \"pin_numero\" VARCHAR(50)",
"ALTER TABLE \"suframa_operacoes\" ADD COLUMN IF NOT EXISTS \"pin_data\" DATE",
"ALTER TABLE \"suframa_operacoes\" ADD COLUMN IF NOT EXISTS \"pin_status\" VARCHAR(20)",
"ALTER TABLE \"suframa_operacoes\" ADD COLUMN IF NOT EXISTS \"internamento_data\" DATE",
"ALTER TABLE \"suframa_operacoes\" ADD COLUMN IF NOT EXISTS \"internamento_protocolo\" VARCHAR(50)",
"ALTER TABLE \"suframa_operacoes\" ADD COLUMN IF NOT EXISTS \"updated_at\" TIMESTAMP WITHOUT TIME ZONE",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"employee_registration\" VARCHAR(50)",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"weekly_hours_minutes\" INTEGER NOT NULL",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"daily_hours_minutes\" INTEGER NOT NULL",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"max_daily_hours_minutes\" INTEGER NOT NULL",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"default_entry_time\" TIME WITHOUT TIME ZONE",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"default_exit_time\" TIME WITHOUT TIME ZONE",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"default_break_start\" TIME WITHOUT TIME ZONE",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"default_break_end\" TIME WITHOUT TIME ZONE",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"daily_schedule\" JSONB",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"work_days\" VARCHAR[]",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"days_off\" VARCHAR[]",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"entry_tolerance_minutes\" INTEGER NOT NULL",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"exit_tolerance_minutes\" INTEGER NOT NULL",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"break_tolerance_minutes\" INTEGER NOT NULL",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"overtime_requires_approval\" BOOLEAN NOT NULL",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"max_overtime_daily_minutes\" INTEGER NOT NULL",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"max_overtime_weekly_minutes\" INTEGER NOT NULL",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"overtime_multiplier_50\" NUMERIC(4, 2) NOT NULL",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"overtime_multiplier_100\" NUMERIC(4, 2) NOT NULL",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"use_time_bank\" BOOLEAN NOT NULL",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"night_shift_multiplier\" NUMERIC(4, 2) NOT NULL",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"night_hour_reduction\" BOOLEAN NOT NULL",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"min_break_4h_minutes\" INTEGER NOT NULL",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"min_break_6h_minutes\" INTEGER NOT NULL",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"min_rest_between_shifts_hours\" INTEGER NOT NULL",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"time_bank_expiry_months\" INTEGER NOT NULL",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"time_bank_max_positive_hours\" INTEGER NOT NULL",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"time_bank_max_negative_hours\" INTEGER NOT NULL",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"require_geolocation\" BOOLEAN NOT NULL",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"max_distance_meters\" INTEGER NOT NULL",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"require_biometric\" BOOLEAN NOT NULL",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"min_biometric_score\" INTEGER NOT NULL",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"require_face_match\" BOOLEAN NOT NULL",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"require_liveness\" BOOLEAN NOT NULL",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"consider_holidays\" BOOLEAN NOT NULL",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"holiday_calendar_id\" VARCHAR(50)",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"collective_agreement_id\" VARCHAR(50)",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"collective_agreement_name\" VARCHAR(200)",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"valid_from\" DATE",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"valid_until\" DATE",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"notes\" TEXT",
"ALTER TABLE \"work_schedules\" ADD COLUMN IF NOT EXISTS \"tags\" JSONB",
"COMMIT;"
]

REVERSAL = [
"ALTER TABLE \"codigos_servico\" DROP COLUMN IF EXISTS \"subitem\"",
"ALTER TABLE \"codigos_servico\" DROP COLUMN IF EXISTS \"aliquota_minima\"",
"ALTER TABLE \"codigos_servico\" DROP COLUMN IF EXISTS \"aliquota_maxima\"",
"ALTER TABLE \"codigos_servico\" DROP COLUMN IF EXISTS \"iss_retido_obrigatorio\"",
"ALTER TABLE \"codigos_servico\" DROP COLUMN IF EXISTS \"local_tributacao\"",
"ALTER TABLE \"codigos_servico\" DROP COLUMN IF EXISTS \"permite_deducao\"",
"ALTER TABLE \"codigos_servico\" DROP COLUMN IF EXISTS \"exige_obra\"",
"ALTER TABLE \"codigos_servico\" DROP COLUMN IF EXISTS \"exige_retencoes_federais\"",
"ALTER TABLE \"codigos_servico\" DROP COLUMN IF EXISTS \"cnaes_relacionados\"",
"ALTER TABLE \"codigos_servico\" DROP COLUMN IF EXISTS \"created_at\"",
"ALTER TABLE \"codigos_servico\" DROP COLUMN IF EXISTS \"updated_at\"",
"ALTER TABLE \"fin_stock_inventories\" DROP COLUMN IF EXISTS \"number\"",
"ALTER TABLE \"fin_stock_inventories\" DROP COLUMN IF EXISTS \"planned_date\"",
"ALTER TABLE \"fin_stock_inventories\" DROP COLUMN IF EXISTS \"start_date\"",
"ALTER TABLE \"fin_stock_inventories\" DROP COLUMN IF EXISTS \"end_date\"",
"ALTER TABLE \"fin_stock_inventories\" DROP COLUMN IF EXISTS \"deadline\"",
"ALTER TABLE \"fin_stock_inventories\" DROP COLUMN IF EXISTS \"filter_categories\"",
"ALTER TABLE \"fin_stock_inventories\" DROP COLUMN IF EXISTS \"filter_locations\"",
"ALTER TABLE \"fin_stock_inventories\" DROP COLUMN IF EXISTS \"filter_abc_class\"",
"ALTER TABLE \"fin_stock_inventories\" DROP COLUMN IF EXISTS \"filter_products\"",
"ALTER TABLE \"fin_stock_inventories\" DROP COLUMN IF EXISTS \"verified_items\"",
"ALTER TABLE \"fin_stock_inventories\" DROP COLUMN IF EXISTS \"expected_value\"",
"ALTER TABLE \"fin_stock_inventories\" DROP COLUMN IF EXISTS \"counted_value\"",
"ALTER TABLE \"fin_stock_inventories\" DROP COLUMN IF EXISTS \"difference_value\"",
"ALTER TABLE \"fin_stock_inventories\" DROP COLUMN IF EXISTS \"adjustment_value\"",
"ALTER TABLE \"fin_stock_inventories\" DROP COLUMN IF EXISTS \"expected_quantity\"",
"ALTER TABLE \"fin_stock_inventories\" DROP COLUMN IF EXISTS \"counted_quantity\"",
"ALTER TABLE \"fin_stock_inventories\" DROP COLUMN IF EXISTS \"difference_quantity\"",
"ALTER TABLE \"fin_stock_inventories\" DROP COLUMN IF EXISTS \"accuracy_rate\"",
"ALTER TABLE \"fin_stock_inventories\" DROP COLUMN IF EXISTS \"hit_rate\"",
"ALTER TABLE \"fin_stock_inventories\" DROP COLUMN IF EXISTS \"auto_adjust\"",
"ALTER TABLE \"fin_stock_inventories\" DROP COLUMN IF EXISTS \"internal_notes\"",
"ALTER TABLE \"fin_stock_inventories\" DROP COLUMN IF EXISTS \"attachments\"",
"ALTER TABLE \"fin_stock_inventories\" DROP COLUMN IF EXISTS \"extra_data\"",
"ALTER TABLE \"fin_stock_inventories\" DROP COLUMN IF EXISTS \"ativo\"",
"ALTER TABLE \"fin_stock_inventory_items\" DROP COLUMN IF EXISTS \"expiry_date\"",
"ALTER TABLE \"fin_stock_inventory_items\" DROP COLUMN IF EXISTS \"aisle\"",
"ALTER TABLE \"fin_stock_inventory_items\" DROP COLUMN IF EXISTS \"rack\"",
"ALTER TABLE \"fin_stock_inventory_items\" DROP COLUMN IF EXISTS \"shelf\"",
"ALTER TABLE \"fin_stock_inventory_items\" DROP COLUMN IF EXISTS \"bin_loc\"",
"ALTER TABLE \"fin_stock_inventory_items\" DROP COLUMN IF EXISTS \"expected_quantity\"",
"ALTER TABLE \"fin_stock_inventory_items\" DROP COLUMN IF EXISTS \"recount_quantity\"",
"ALTER TABLE \"fin_stock_inventory_items\" DROP COLUMN IF EXISTS \"difference_quantity\"",
"ALTER TABLE \"fin_stock_inventory_items\" DROP COLUMN IF EXISTS \"expected_value\"",
"ALTER TABLE \"fin_stock_inventory_items\" DROP COLUMN IF EXISTS \"difference_value\"",
"ALTER TABLE \"fin_stock_inventory_items\" DROP COLUMN IF EXISTS \"recounted_at\"",
"ALTER TABLE \"fin_stock_inventory_items\" DROP COLUMN IF EXISTS \"recounted_by\"",
"ALTER TABLE \"fin_stock_inventory_items\" DROP COLUMN IF EXISTS \"verified_at\"",
"ALTER TABLE \"fin_stock_inventory_items\" DROP COLUMN IF EXISTS \"verified_by\"",
"ALTER TABLE \"fin_stock_inventory_items\" DROP COLUMN IF EXISTS \"adjusted_at\"",
"ALTER TABLE \"fin_stock_inventory_items\" DROP COLUMN IF EXISTS \"adjusted_by\"",
"ALTER TABLE \"fin_stock_inventory_items\" DROP COLUMN IF EXISTS \"ativo\"",
"ALTER TABLE \"fin_stock_movements\" DROP COLUMN IF EXISTS \"number\"",
"ALTER TABLE \"fin_stock_movements\" DROP COLUMN IF EXISTS \"reason\"",
"ALTER TABLE \"fin_stock_movements\" DROP COLUMN IF EXISTS \"expiry_date\"",
"ALTER TABLE \"fin_stock_movements\" DROP COLUMN IF EXISTS \"source_location\"",
"ALTER TABLE \"fin_stock_movements\" DROP COLUMN IF EXISTS \"source_aisle\"",
"ALTER TABLE \"fin_stock_movements\" DROP COLUMN IF EXISTS \"source_rack\"",
"ALTER TABLE \"fin_stock_movements\" DROP COLUMN IF EXISTS \"source_shelf\"",
"ALTER TABLE \"fin_stock_movements\" DROP COLUMN IF EXISTS \"source_bin\"",
"ALTER TABLE \"fin_stock_movements\" DROP COLUMN IF EXISTS \"dest_location\"",
"ALTER TABLE \"fin_stock_movements\" DROP COLUMN IF EXISTS \"dest_aisle\"",
"ALTER TABLE \"fin_stock_movements\" DROP COLUMN IF EXISTS \"dest_rack\"",
"ALTER TABLE \"fin_stock_movements\" DROP COLUMN IF EXISTS \"dest_shelf\"",
"ALTER TABLE \"fin_stock_movements\" DROP COLUMN IF EXISTS \"dest_bin\"",
"ALTER TABLE \"fin_stock_movements\" DROP COLUMN IF EXISTS \"reference_type\"",
"ALTER TABLE \"fin_stock_movements\" DROP COLUMN IF EXISTS \"reference_id\"",
"ALTER TABLE \"fin_stock_movements\" DROP COLUMN IF EXISTS \"reference_number\"",
"ALTER TABLE \"fin_stock_movements\" DROP COLUMN IF EXISTS \"invoice_number\"",
"ALTER TABLE \"fin_stock_movements\" DROP COLUMN IF EXISTS \"invoice_series\"",
"ALTER TABLE \"fin_stock_movements\" DROP COLUMN IF EXISTS \"invoice_key\"",
"ALTER TABLE \"fin_stock_movements\" DROP COLUMN IF EXISTS \"supplier_id\"",
"ALTER TABLE \"fin_stock_movements\" DROP COLUMN IF EXISTS \"customer_id\"",
"ALTER TABLE \"fin_stock_movements\" DROP COLUMN IF EXISTS \"requisition_id\"",
"ALTER TABLE \"fin_stock_movements\" DROP COLUMN IF EXISTS \"requisition_number\"",
"ALTER TABLE \"fin_stock_movements\" DROP COLUMN IF EXISTS \"reversal_of\"",
"ALTER TABLE \"fin_stock_movements\" DROP COLUMN IF EXISTS \"reversed_by\"",
"ALTER TABLE \"fin_stock_movements\" DROP COLUMN IF EXISTS \"internal_notes\"",
"ALTER TABLE \"fin_stock_movements\" DROP COLUMN IF EXISTS \"attachments\"",
"ALTER TABLE \"fin_stock_movements\" DROP COLUMN IF EXISTS \"extra_data\"",
"ALTER TABLE \"fin_stock_movements\" DROP COLUMN IF EXISTS \"confirmed_by\"",
"ALTER TABLE \"fin_stock_movements\" DROP COLUMN IF EXISTS \"ativo\"",
"ALTER TABLE \"fin_stock_reservations\" DROP COLUMN IF EXISTS \"number\"",
"ALTER TABLE \"fin_stock_reservations\" DROP COLUMN IF EXISTS \"description\"",
"ALTER TABLE \"fin_stock_reservations\" DROP COLUMN IF EXISTS \"batch_number\"",
"ALTER TABLE \"fin_stock_reservations\" DROP COLUMN IF EXISTS \"quantity_requested\"",
"ALTER TABLE \"fin_stock_reservations\" DROP COLUMN IF EXISTS \"quantity_pending\"",
"ALTER TABLE \"fin_stock_reservations\" DROP COLUMN IF EXISTS \"required_date\"",
"ALTER TABLE \"fin_stock_reservations\" DROP COLUMN IF EXISTS \"reference_type\"",
"ALTER TABLE \"fin_stock_reservations\" DROP COLUMN IF EXISTS \"reference_id\"",
"ALTER TABLE \"fin_stock_reservations\" DROP COLUMN IF EXISTS \"reference_number\"",
"ALTER TABLE \"fin_stock_reservations\" DROP COLUMN IF EXISTS \"requester_id\"",
"ALTER TABLE \"fin_stock_reservations\" DROP COLUMN IF EXISTS \"requester_name\"",
"ALTER TABLE \"fin_stock_reservations\" DROP COLUMN IF EXISTS \"requires_approval\"",
"ALTER TABLE \"fin_stock_reservations\" DROP COLUMN IF EXISTS \"approved_by\"",
"ALTER TABLE \"fin_stock_reservations\" DROP COLUMN IF EXISTS \"approved_at\"",
"ALTER TABLE \"fin_stock_reservations\" DROP COLUMN IF EXISTS \"approval_notes\"",
"ALTER TABLE \"fin_stock_reservations\" DROP COLUMN IF EXISTS \"released_by\"",
"ALTER TABLE \"fin_stock_reservations\" DROP COLUMN IF EXISTS \"release_notes\"",
"ALTER TABLE \"fin_stock_reservations\" DROP COLUMN IF EXISTS \"cancelled_by\"",
"ALTER TABLE \"fin_stock_reservations\" DROP COLUMN IF EXISTS \"auto_expire\"",
"ALTER TABLE \"fin_stock_reservations\" DROP COLUMN IF EXISTS \"allow_partial\"",
"ALTER TABLE \"fin_stock_reservations\" DROP COLUMN IF EXISTS \"internal_notes\"",
"ALTER TABLE \"fin_stock_reservations\" DROP COLUMN IF EXISTS \"extra_data\"",
"ALTER TABLE \"fin_stock_reservations\" DROP COLUMN IF EXISTS \"ativo\"",
"ALTER TABLE \"goods_receipt_items\" DROP COLUMN IF EXISTS \"updated_at\"",
"ALTER TABLE \"goods_receipts\" DROP COLUMN IF EXISTS \"approval_notes\"",
"ALTER TABLE \"goods_receipts\" DROP COLUMN IF EXISTS \"rejected_at\"",
"ALTER TABLE \"goods_receipts\" DROP COLUMN IF EXISTS \"rejected_by\"",
"ALTER TABLE \"goods_receipts\" DROP COLUMN IF EXISTS \"internal_notes\"",
"ALTER TABLE \"goods_receipts\" DROP COLUMN IF EXISTS \"receiver_signature\"",
"ALTER TABLE \"payable_categories\" DROP COLUMN IF EXISTS \"created_by\"",
"ALTER TABLE \"payment_methods\" DROP COLUMN IF EXISTS \"created_by\"",
"ALTER TABLE \"products\" DROP COLUMN IF EXISTS \"technical_specs\"",
"ALTER TABLE \"products\" DROP COLUMN IF EXISTS \"conversion_factor\"",
"ALTER TABLE \"products\" DROP COLUMN IF EXISTS \"min_stock\"",
"ALTER TABLE \"products\" DROP COLUMN IF EXISTS \"max_stock\"",
"ALTER TABLE \"products\" DROP COLUMN IF EXISTS \"cest\"",
"ALTER TABLE \"products\" DROP COLUMN IF EXISTS \"cfop_default\"",
"ALTER TABLE \"products\" DROP COLUMN IF EXISTS \"preferred_supplier_id\"",
"ALTER TABLE \"products\" DROP COLUMN IF EXISTS \"thumbnail_url\"",
"ALTER TABLE \"products\" DROP COLUMN IF EXISTS \"documents\"",
"ALTER TABLE \"products\" DROP COLUMN IF EXISTS \"attributes\"",
"ALTER TABLE \"products\" DROP COLUMN IF EXISTS \"brand\"",
"ALTER TABLE \"products\" DROP COLUMN IF EXISTS \"manufacturer\"",
"ALTER TABLE \"products\" DROP COLUMN IF EXISTS \"model\"",
"ALTER TABLE \"products\" DROP COLUMN IF EXISTS \"internal_notes\"",
"ALTER TABLE \"products\" DROP COLUMN IF EXISTS \"blocked_reason\"",
"ALTER TABLE \"products\" DROP COLUMN IF EXISTS \"total_purchases\"",
"ALTER TABLE \"products\" DROP COLUMN IF EXISTS \"last_purchase_at\"",
"ALTER TABLE \"purchase_approvals\" DROP COLUMN IF EXISTS \"info_requested_at\"",
"ALTER TABLE \"purchase_approvals\" DROP COLUMN IF EXISTS \"info_provided_at\"",
"ALTER TABLE \"purchase_approvals\" DROP COLUMN IF EXISTS \"notification_sent_at\"",
"ALTER TABLE \"purchase_approvals\" DROP COLUMN IF EXISTS \"last_reminder_at\"",
"ALTER TABLE \"purchase_approvals\" DROP COLUMN IF EXISTS \"attachments\"",
"ALTER TABLE \"purchase_approvals\" DROP COLUMN IF EXISTS \"created_by\"",
"ALTER TABLE \"purchase_order_items\" DROP COLUMN IF EXISTS \"updated_at\"",
"ALTER TABLE \"purchase_quotation_items\" DROP COLUMN IF EXISTS \"supplier_description\"",
"ALTER TABLE \"purchase_quotation_items\" DROP COLUMN IF EXISTS \"quantity_requested\"",
"ALTER TABLE \"purchase_quotation_items\" DROP COLUMN IF EXISTS \"quantity_offered\"",
"ALTER TABLE \"purchase_quotation_items\" DROP COLUMN IF EXISTS \"min_quantity\"",
"ALTER TABLE \"purchase_quotation_items\" DROP COLUMN IF EXISTS \"discount_percentage\"",
"ALTER TABLE \"purchase_quotation_items\" DROP COLUMN IF EXISTS \"discount_amount\"",
"ALTER TABLE \"purchase_quotation_items\" DROP COLUMN IF EXISTS \"availability\"",
"ALTER TABLE \"purchase_quotation_items\" DROP COLUMN IF EXISTS \"technical_specs\"",
"ALTER TABLE \"purchase_quotation_items\" DROP COLUMN IF EXISTS \"meets_specs\"",
"ALTER TABLE \"purchase_quotation_items\" DROP COLUMN IF EXISTS \"evaluation_notes\"",
"ALTER TABLE \"purchase_quotation_items\" DROP COLUMN IF EXISTS \"updated_at\"",
"ALTER TABLE \"purchase_quotations\" DROP COLUMN IF EXISTS \"reference\"",
"ALTER TABLE \"purchase_quotations\" DROP COLUMN IF EXISTS \"request_date\"",
"ALTER TABLE \"purchase_quotations\" DROP COLUMN IF EXISTS \"sent_date\"",
"ALTER TABLE \"purchase_quotations\" DROP COLUMN IF EXISTS \"received_date\"",
"ALTER TABLE \"purchase_quotations\" DROP COLUMN IF EXISTS \"validity_date\"",
"ALTER TABLE \"purchase_quotations\" DROP COLUMN IF EXISTS \"expected_delivery_date\"",
"ALTER TABLE \"purchase_quotations\" DROP COLUMN IF EXISTS \"payment_installments\"",
"ALTER TABLE \"purchase_quotations\" DROP COLUMN IF EXISTS \"internal_notes\"",
"ALTER TABLE \"purchase_quotations\" DROP COLUMN IF EXISTS \"rejected_at\"",
"ALTER TABLE \"purchase_quotations\" DROP COLUMN IF EXISTS \"rejected_by\"",
"ALTER TABLE \"purchase_quotations\" DROP COLUMN IF EXISTS \"selection_justification\"",
"ALTER TABLE \"purchase_quotations\" DROP COLUMN IF EXISTS \"comparison_notes\"",
"ALTER TABLE \"purchase_quotations\" DROP COLUMN IF EXISTS \"is_best_price\"",
"ALTER TABLE \"purchase_quotations\" DROP COLUMN IF EXISTS \"is_best_delivery\"",
"ALTER TABLE \"purchase_quotations\" DROP COLUMN IF EXISTS \"is_best_overall\"",
"ALTER TABLE \"purchase_requisition_items\" DROP COLUMN IF EXISTS \"quantity_requested\"",
"ALTER TABLE \"purchase_requisition_items\" DROP COLUMN IF EXISTS \"quantity_received\"",
"ALTER TABLE \"purchase_requisition_items\" DROP COLUMN IF EXISTS \"estimated_unit_price\"",
"ALTER TABLE \"purchase_requisition_items\" DROP COLUMN IF EXISTS \"approved_unit_price\"",
"ALTER TABLE \"purchase_requisition_items\" DROP COLUMN IF EXISTS \"actual_unit_price\"",
"ALTER TABLE \"purchase_requisition_items\" DROP COLUMN IF EXISTS \"updated_at\"",
"ALTER TABLE \"purchase_requisitions\" DROP COLUMN IF EXISTS \"revision\"",
"ALTER TABLE \"purchase_requisitions\" DROP COLUMN IF EXISTS \"title\"",
"ALTER TABLE \"purchase_requisitions\" DROP COLUMN IF EXISTS \"request_date\"",
"ALTER TABLE \"purchase_requisitions\" DROP COLUMN IF EXISTS \"needed_by_date\"",
"ALTER TABLE \"purchase_requisitions\" DROP COLUMN IF EXISTS \"approved_at\"",
"ALTER TABLE \"purchase_requisitions\" DROP COLUMN IF EXISTS \"approved_budget\"",
"ALTER TABLE \"purchase_requisitions\" DROP COLUMN IF EXISTS \"actual_total\"",
"ALTER TABLE \"purchase_requisitions\" DROP COLUMN IF EXISTS \"min_quotations\"",
"ALTER TABLE \"purchase_requisitions\" DROP COLUMN IF EXISTS \"delivery_address\"",
"ALTER TABLE \"purchase_requisitions\" DROP COLUMN IF EXISTS \"delivery_contact\"",
"ALTER TABLE \"purchase_requisitions\" DROP COLUMN IF EXISTS \"delivery_phone\"",
"ALTER TABLE \"purchase_requisitions\" DROP COLUMN IF EXISTS \"delivery_instructions\"",
"ALTER TABLE \"purchase_requisitions\" DROP COLUMN IF EXISTS \"suggested_supplier_id\"",
"ALTER TABLE \"purchase_requisitions\" DROP COLUMN IF EXISTS \"supplier_justification\"",
"ALTER TABLE \"purchase_requisitions\" DROP COLUMN IF EXISTS \"internal_notes\"",
"ALTER TABLE \"purchase_requisitions\" DROP COLUMN IF EXISTS \"rejected_at\"",
"ALTER TABLE \"purchase_requisitions\" DROP COLUMN IF EXISTS \"cancelled_at\"",
"ALTER TABLE \"purchase_requisitions\" DROP COLUMN IF EXISTS \"cancelled_by\"",
"ALTER TABLE \"purchase_requisitions\" DROP COLUMN IF EXISTS \"approval_history\"",
"ALTER TABLE \"receivable_categories\" DROP COLUMN IF EXISTS \"apply_interest\"",
"ALTER TABLE \"receivable_categories\" DROP COLUMN IF EXISTS \"interest_rate\"",
"ALTER TABLE \"receivable_categories\" DROP COLUMN IF EXISTS \"apply_penalty\"",
"ALTER TABLE \"receivable_categories\" DROP COLUMN IF EXISTS \"penalty_rate\"",
"ALTER TABLE \"simples_nacional_das\" DROP COLUMN IF EXISTS \"competencia\"",
"ALTER TABLE \"simples_nacional_das\" DROP COLUMN IF EXISTS \"ano\"",
"ALTER TABLE \"simples_nacional_das\" DROP COLUMN IF EXISTS \"mes\"",
"ALTER TABLE \"simples_nacional_das\" DROP COLUMN IF EXISTS \"fator_r\"",
"ALTER TABLE \"simples_nacional_das\" DROP COLUMN IF EXISTS \"folha_pagamento_12_meses\"",
"ALTER TABLE \"simples_nacional_das\" DROP COLUMN IF EXISTS \"valor_das\"",
"ALTER TABLE \"simples_nacional_das\" DROP COLUMN IF EXISTS \"reparticao\"",
"ALTER TABLE \"simples_nacional_das\" DROP COLUMN IF EXISTS \"valor_irpj\"",
"ALTER TABLE \"simples_nacional_das\" DROP COLUMN IF EXISTS \"valor_csll\"",
"ALTER TABLE \"simples_nacional_das\" DROP COLUMN IF EXISTS \"valor_cofins\"",
"ALTER TABLE \"simples_nacional_das\" DROP COLUMN IF EXISTS \"valor_pis\"",
"ALTER TABLE \"simples_nacional_das\" DROP COLUMN IF EXISTS \"valor_cpp\"",
"ALTER TABLE \"simples_nacional_das\" DROP COLUMN IF EXISTS \"valor_icms\"",
"ALTER TABLE \"simples_nacional_das\" DROP COLUMN IF EXISTS \"valor_iss\"",
"ALTER TABLE \"simples_nacional_das\" DROP COLUMN IF EXISTS \"numero_das\"",
"ALTER TABLE \"simples_nacional_das\" DROP COLUMN IF EXISTS \"iss_retido\"",
"ALTER TABLE \"simples_nacional_das\" DROP COLUMN IF EXISTS \"valor_iss_retido\"",
"ALTER TABLE \"sped_files\" DROP COLUMN IF EXISTS \"versao_layout\"",
"ALTER TABLE \"sped_files\" DROP COLUMN IF EXISTS \"periodo_inicio\"",
"ALTER TABLE \"sped_files\" DROP COLUMN IF EXISTS \"periodo_fim\"",
"ALTER TABLE \"sped_files\" DROP COLUMN IF EXISTS \"data_geracao\"",
"ALTER TABLE \"sped_files\" DROP COLUMN IF EXISTS \"data_validacao\"",
"ALTER TABLE \"sped_files\" DROP COLUMN IF EXISTS \"cnpj\"",
"ALTER TABLE \"sped_files\" DROP COLUMN IF EXISTS \"razao_social\"",
"ALTER TABLE \"sped_files\" DROP COLUMN IF EXISTS \"inscricao_estadual\"",
"ALTER TABLE \"sped_files\" DROP COLUMN IF EXISTS \"uf\"",
"ALTER TABLE \"sped_files\" DROP COLUMN IF EXISTS \"caminho_arquivo\"",
"ALTER TABLE \"sped_files\" DROP COLUMN IF EXISTS \"pva_versao\"",
"ALTER TABLE \"sped_files\" DROP COLUMN IF EXISTS \"pva_resultado\"",
"ALTER TABLE \"sped_files\" DROP COLUMN IF EXISTS \"pva_erros\"",
"ALTER TABLE \"sped_files\" DROP COLUMN IF EXISTS \"pva_avisos\"",
"ALTER TABLE \"sped_files\" DROP COLUMN IF EXISTS \"pva_log\"",
"ALTER TABLE \"sped_files\" DROP COLUMN IF EXISTS \"protocolo\"",
"ALTER TABLE \"sped_files\" DROP COLUMN IF EXISTS \"recibo\"",
"ALTER TABLE \"sped_files\" DROP COLUMN IF EXISTS \"codigo_retorno\"",
"ALTER TABLE \"sped_files\" DROP COLUMN IF EXISTS \"mensagem_retorno\"",
"ALTER TABLE \"sped_files\" DROP COLUMN IF EXISTS \"sped_retificado_id\"",
"ALTER TABLE \"sped_files\" DROP COLUMN IF EXISTS \"nire\"",
"ALTER TABLE \"sped_files\" DROP COLUMN IF EXISTS \"estatisticas\"",
"ALTER TABLE \"sped_files\" DROP COLUMN IF EXISTS \"valores_resumo\"",
"ALTER TABLE \"sped_files\" DROP COLUMN IF EXISTS \"created_by\"",
"ALTER TABLE \"suframa_configs\" DROP COLUMN IF EXISTS \"tipo_zona\"",
"ALTER TABLE \"suframa_configs\" DROP COLUMN IF EXISTS \"status\"",
"ALTER TABLE \"suframa_configs\" DROP COLUMN IF EXISTS \"data_inscricao\"",
"ALTER TABLE \"suframa_configs\" DROP COLUMN IF EXISTS \"cnpj\"",
"ALTER TABLE \"suframa_configs\" DROP COLUMN IF EXISTS \"razao_social\"",
"ALTER TABLE \"suframa_configs\" DROP COLUMN IF EXISTS \"nome_fantasia\"",
"ALTER TABLE \"suframa_configs\" DROP COLUMN IF EXISTS \"endereco\"",
"ALTER TABLE \"suframa_configs\" DROP COLUMN IF EXISTS \"codigo_municipio\"",
"ALTER TABLE \"suframa_configs\" DROP COLUMN IF EXISTS \"municipio_nome\"",
"ALTER TABLE \"suframa_configs\" DROP COLUMN IF EXISTS \"uf\"",
"ALTER TABLE \"suframa_configs\" DROP COLUMN IF EXISTS \"cnaes_habilitados\"",
"ALTER TABLE \"suframa_configs\" DROP COLUMN IF EXISTS \"beneficio_ipi\"",
"ALTER TABLE \"suframa_configs\" DROP COLUMN IF EXISTS \"beneficio_icms\"",
"ALTER TABLE \"suframa_configs\" DROP COLUMN IF EXISTS \"beneficio_pis_cofins\"",
"ALTER TABLE \"suframa_configs\" DROP COLUMN IF EXISTS \"beneficio_ii\"",
"ALTER TABLE \"suframa_configs\" DROP COLUMN IF EXISTS \"reducao_icms_interno\"",
"ALTER TABLE \"suframa_configs\" DROP COLUMN IF EXISTS \"reducao_icms_interestadual\"",
"ALTER TABLE \"suframa_configs\" DROP COLUMN IF EXISTS \"credito_presumido_icms\"",
"ALTER TABLE \"suframa_configs\" DROP COLUMN IF EXISTS \"simples_nacional\"",
"ALTER TABLE \"suframa_configs\" DROP COLUMN IF EXISTS \"simples_anexo\"",
"ALTER TABLE \"suframa_configs\" DROP COLUMN IF EXISTS \"simples_faixa\"",
"ALTER TABLE \"suframa_configs\" DROP COLUMN IF EXISTS \"documentos\"",
"ALTER TABLE \"suframa_configs\" DROP COLUMN IF EXISTS \"created_by\"",
"ALTER TABLE \"suframa_operacoes\" DROP COLUMN IF EXISTS \"suframa_config_id\"",
"ALTER TABLE \"suframa_operacoes\" DROP COLUMN IF EXISTS \"documento_tipo\"",
"ALTER TABLE \"suframa_operacoes\" DROP COLUMN IF EXISTS \"documento_id\"",
"ALTER TABLE \"suframa_operacoes\" DROP COLUMN IF EXISTS \"chave_acesso\"",
"ALTER TABLE \"suframa_operacoes\" DROP COLUMN IF EXISTS \"numero_documento\"",
"ALTER TABLE \"suframa_operacoes\" DROP COLUMN IF EXISTS \"participante_cnpj\"",
"ALTER TABLE \"suframa_operacoes\" DROP COLUMN IF EXISTS \"participante_suframa\"",
"ALTER TABLE \"suframa_operacoes\" DROP COLUMN IF EXISTS \"participante_razao_social\"",
"ALTER TABLE \"suframa_operacoes\" DROP COLUMN IF EXISTS \"cfop\"",
"ALTER TABLE \"suframa_operacoes\" DROP COLUMN IF EXISTS \"valor_produtos\"",
"ALTER TABLE \"suframa_operacoes\" DROP COLUMN IF EXISTS \"ipi_isento\"",
"ALTER TABLE \"suframa_operacoes\" DROP COLUMN IF EXISTS \"ipi_economia\"",
"ALTER TABLE \"suframa_operacoes\" DROP COLUMN IF EXISTS \"icms_isento\"",
"ALTER TABLE \"suframa_operacoes\" DROP COLUMN IF EXISTS \"icms_reducao_percentual\"",
"ALTER TABLE \"suframa_operacoes\" DROP COLUMN IF EXISTS \"icms_economia\"",
"ALTER TABLE \"suframa_operacoes\" DROP COLUMN IF EXISTS \"pis_suspenso\"",
"ALTER TABLE \"suframa_operacoes\" DROP COLUMN IF EXISTS \"pis_economia\"",
"ALTER TABLE \"suframa_operacoes\" DROP COLUMN IF EXISTS \"cofins_suspenso\"",
"ALTER TABLE \"suframa_operacoes\" DROP COLUMN IF EXISTS \"cofins_economia\"",
"ALTER TABLE \"suframa_operacoes\" DROP COLUMN IF EXISTS \"total_economia\"",
"ALTER TABLE \"suframa_operacoes\" DROP COLUMN IF EXISTS \"pin_numero\"",
"ALTER TABLE \"suframa_operacoes\" DROP COLUMN IF EXISTS \"pin_data\"",
"ALTER TABLE \"suframa_operacoes\" DROP COLUMN IF EXISTS \"pin_status\"",
"ALTER TABLE \"suframa_operacoes\" DROP COLUMN IF EXISTS \"internamento_data\"",
"ALTER TABLE \"suframa_operacoes\" DROP COLUMN IF EXISTS \"internamento_protocolo\"",
"ALTER TABLE \"suframa_operacoes\" DROP COLUMN IF EXISTS \"updated_at\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"employee_registration\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"weekly_hours_minutes\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"daily_hours_minutes\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"max_daily_hours_minutes\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"default_entry_time\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"default_exit_time\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"default_break_start\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"default_break_end\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"daily_schedule\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"work_days\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"days_off\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"entry_tolerance_minutes\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"exit_tolerance_minutes\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"break_tolerance_minutes\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"overtime_requires_approval\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"max_overtime_daily_minutes\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"max_overtime_weekly_minutes\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"overtime_multiplier_50\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"overtime_multiplier_100\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"use_time_bank\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"night_shift_multiplier\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"night_hour_reduction\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"min_break_4h_minutes\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"min_break_6h_minutes\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"min_rest_between_shifts_hours\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"time_bank_expiry_months\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"time_bank_max_positive_hours\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"time_bank_max_negative_hours\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"require_geolocation\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"max_distance_meters\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"require_biometric\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"min_biometric_score\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"require_face_match\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"require_liveness\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"consider_holidays\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"holiday_calendar_id\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"collective_agreement_id\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"collective_agreement_name\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"valid_from\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"valid_until\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"notes\"",
"ALTER TABLE \"work_schedules\" DROP COLUMN IF EXISTS \"tags\"",
"DROP TABLE IF EXISTS \"ecd_resumos\" CASCADE",
"DROP TABLE IF EXISTS \"efd_contribuicoes_resumos\" CASCADE",
"DROP TABLE IF EXISTS \"efd_icms_ipi_resumos\" CASCADE",
"DROP TABLE IF EXISTS \"fin_cost_analyses\" CASCADE",
"DROP TABLE IF EXISTS \"fin_cost_drivers\" CASCADE",
"DROP TABLE IF EXISTS \"fin_cost_objects\" CASCADE",
"DROP TABLE IF EXISTS \"fin_cost_pools\" CASCADE",
"DROP TABLE IF EXISTS \"fin_cost_activities\" CASCADE",
"DROP TABLE IF EXISTS \"fin_cost_allocations\" CASCADE",
"DROP TABLE IF EXISTS \"financial_analytics_cache\" CASCADE",
"DROP TABLE IF EXISTS \"financial_scheduled_reports\" CASCADE",
"DROP TABLE IF EXISTS \"payroll_integrations\" CASCADE",
"DROP TABLE IF EXISTS \"payroll_exports\" CASCADE",
"DROP TABLE IF EXISTS \"simples_nacional_configs\" CASCADE",
"DROP TABLE IF EXISTS \"sped_registros\" CASCADE",
"DROP TABLE IF EXISTS \"tax_configurations\" CASCADE",
"DROP TABLE IF EXISTS \"tax_tables\" CASCADE",
"COMMIT;"
]

def upgrade():
    for s in FORWARD:
        op.execute(s)

def downgrade():
    for s in REVERSAL:
        op.execute(s)
