/**
 * LGPD Security Module - API Client
 *
 * Módulo completo de Segurança e Compliance LGPD (Lei 13.709/2018)
 *
 * Compliance:
 * - Art. 7, 8, 9: Gestão de Consentimentos
 * - Art. 18: Direito ao Esquecimento
 * - Art. 38: Avaliação de Impacto (PIA/DPIA)
 * - Art. 46: Trilha de Auditoria
 *
 * Funcionalidades:
 * - Criptografia de dados sensíveis (AES-256-GCM, ChaCha20, etc)
 * - Mascaramento de PII (CPF, email, telefone, etc)
 * - Registro e revogação de consentimentos
 * - Direito ao esquecimento
 * - Avaliação de impacto de privacidade
 * - Trilha de auditoria com hash chain
 *
 * @module security-lgpd
 */

// ============================================================================
// SERVICES
// ============================================================================

import * as consentService from './services/consentService';
import * as encryptionService from './services/encryptionService';
import * as auditService from './services/auditService';
import * as erasureService from './services/erasureService';
import * as piaService from './services/piaService';
import * as maskingService from './services/maskingService';
import * as statusService from './services/statusService';

export { consentService, encryptionService, auditService, erasureService, piaService, maskingService, statusService };

// ============================================================================
// HOOKS
// ============================================================================

export * from './hooks/useConsent';
export * from './hooks/useEncryption';
export * from './hooks/useAudit';
export * from './hooks/useErasure';
export * from './hooks/usePIA';
export * from './hooks/useMasking';

// ============================================================================
// TYPES (Generated by Orval)
// ============================================================================

export type {
  ConsentRequest,
  EncryptDataRequest,
  DecryptDataRequest,
  AuditLogRequest,
  ErasureRequestSchema,
  PIARequest,
  MaskDataRequest,
  StandardResponse,
  ErrorResponse,
} from '@/types/generated/security-lgpd/conectaPROLGPDSecurityAPI.schemas';

// ============================================================================
// SERVICE TYPES
// ============================================================================

export type {
  ConsentData,
  ConsentsListResponse,
  Purpose,
  LegalBasis,
} from './services/consentService';

export type {
  EncryptionAlgorithm,
  EncryptedData,
  AlgorithmInfo,
} from './services/encryptionService';

export type {
  SeverityLevel,
  AuditLog,
  AuditLogsResponse,
  AuditFilters,
} from './services/auditService';

export type {
  ErasureScope,
  ErasureStatus,
  ErasureRequest,
} from './services/erasureService';

export type {
  RiskLevel,
  PIAAssessment,
  RiskCategory,
} from './services/piaService';

export type {
  MaskCategory,
  MaskLevel,
  MaskedData,
  MaskingFormat,
} from './services/maskingService';

export type { LGPDStatus, HealthCheck } from './services/statusService';

// ============================================================================
// UTILITY FUNCTIONS
// ============================================================================

import {
  isConsentActive,
  getActiveConsents,
  groupConsentsByPurpose,
} from './services/consentService';

import { isEncrypted, encryptFields } from './services/encryptionService';

import { verifyHashChain } from './services/auditService';

import { isErasureCompleted, getDaysUntilDeadline } from './services/erasureService';

import {
  isPIAMandatory,
  calculateRiskScore,
  determineRiskLevel,
} from './services/piaService';

import { maskFields, autoMask } from './services/maskingService';

import {
  isModuleOperational,
  areAllComponentsActive,
  getInactiveComponents,
  checkCompliance,
} from './services/statusService';

export const lgpdUtils = {
  // Consent
  isConsentActive,
  getActiveConsents,
  groupConsentsByPurpose,

  // Encryption
  isEncrypted,
  encryptFields,

  // Audit
  verifyHashChain,

  // Erasure
  isErasureCompleted,
  getDaysUntilDeadline,

  // PIA
  isPIAMandatory,
  calculateRiskScore,
  determineRiskLevel,

  // Masking
  maskFields,
  autoMask,

  // Status
  isModuleOperational,
  areAllComponentsActive,
  getInactiveComponents,
  checkCompliance,
};

// ============================================================================
// DEFAULT EXPORT
// ============================================================================

const securityLgpdApi = {
  // Services
  consentService,
  encryptionService,
  auditService,
  erasureService,
  piaService,
  maskingService,
  statusService,

  // Utils
  utils: lgpdUtils,
};

export default securityLgpdApi;
